### PR TITLE
Python add-on for developments tests

### PR DESCRIPTION
**Pull request by CastagnaIT**
## Description

I've been thinking about this for years now
I think it can be useful to provide a simple testing method for us,
and also for new developers or users who want to try using ISA or participate in some way to tests
Having an extensible python add-on for tests i think is best
and also can also shown how to integrate isa to python add-ons

Whole menu data is contained on menu_data.py file, json based so can be extended as you wish,
that file contains some more instructions, but it is imo quite understandable

**i intentionally limited the add-on compatibility to minimum Kodi v21**, this because on old Kodi's we have older (deprecated/now removed) properties that otherwise will made more complex all the add-on for nothing, and anyway its designed for the future not for outdated versions of Kodi

there are different ways to think about writing this add-on and certainly everyone will have different ideas, but i think it's a wayto start

I thought of adding it directly into this repository, because it needs to be kept in line with the binary changes
Is not thought to be officially published in the Kodi repository

all things can be discusses if you think it is appropriate

here some screenshots while running (just zip the main folder and install it as usual):
immagine
immagine
immagine
immagine

## Types of change

- [ ] **Bug fix** (non-breaking change which fixes an issue)
- [ ] **Clean up** (non-breaking change which removes non-working, unmaintained functionality)
- [ ] **Improvement** (non-breaking change which improves existing functionality)
- [ ] **New feature** (non-breaking change which adds functionality)
- [ ] **Breaking change** (fix or feature that will cause existing functionality to change)
- [ ] **Cosmetic change** (non-breaking change that doesn't touch code)
- [x] **None of the above** (please explain below)

Its a tester add-on, separate from the binary add-on sources

## Checklist:

- [ ] I have read the **[Contributing](https://github.com/xbmc/xbmc/blob/master/docs/CONTRIBUTING.md)** document
- [ ] My code follows the **[Code Guidelines](https://github.com/xbmc/xbmc/blob/master/docs/CODE_GUIDELINES.md)** of this project 
- [ ] My change requires a change to the Wiki documentation
- [ ] I have updated the documentation accordingly

### CODE REVIEW

**Comment by CastagnaIT** [comment]
CC @glennguy @matthuisman thoughts?

**Comment by matthuisman** [comment]
this is really neat!!

I remember years ago i started creating a repo of .strm files for different types of streams (https://github.com/matthuisman/ia_tests)

This is similiar but in add-on form :)
Hopefully it also makes it easier for you guys to test PRs dont break any existing working streams :)
Unittests are great, but runtime testing is also great

**Comment by CastagnaIT** [comment]
you have a good list, most of them are customized and cant fit this addon
but maybe someone could be added here

**Comment by glennguy** [comment]
Great idea. I agree with keeping it in this repo

**Comment by CastagnaIT** [comment]
if you have some other free stream that you want include let me know

**Pull request merged**
