### PR TITLE
Move bundled libbento4 into depends

### PR DESCRIPTION
**Pull request by glennguy**
## Description

Move the bundled libraries into the cmake build system depends

Patches included (many thanks to @CastagnaIT for his hard work in preparing them) to bring the external version to the modified version that was previously bundled.
Using the latest tagged version of bento4 (1.6.0-639) with an additional patch from master to support cmake install.

## Motivation and context

First steps in the larger cleanup/refactor

## How has this been tested?
Compiles under Windows, run-time test seems fine

## What is the effect on users?

No effect

## Types of change

- [ ] **Bug fix** (non-breaking change which fixes an issue)
- [x] **Clean up** (non-breaking change which removes non-working, unmaintained functionality)
- [ ] **Improvement** (non-breaking change which improves existing functionality)
- [ ] **New feature** (non-breaking change which adds functionality)
- [ ] **Breaking change** (fix or feature that will cause existing functionality to change)
- [ ] **Cosmetic change** (non-breaking change that doesn't touch code)
- [ ] **None of the above** (please explain below)

## Checklist:

- [x] My code follows the **[Code Guidelines](https://github.com/xbmc/xbmc/blob/master/docs/CODE_GUIDELINES.md)** of this project 
- [ ] My change requires a change to the documentation, either Doxygen or wiki
- [ ] I have updated the documentation accordingly
- [x] I have read the **[Contributing](https://github.com/xbmc/xbmc/blob/master/docs/CONTRIBUTING.md)** document
- [ ] I have added tests to cover my change
- [x] All new and existing tests passed

### CODE REVIEW

**Comment by CastagnaIT** [comment]
great! tried build with success but only two things:
1) is missing `bento4.sha256` file under \depends\common\bento4
you can create it and add inside:
`AD727E833D38FE16CED2C05E170AF554BF6225E8F4CF03F51369D41FBDEF62B0`

2) the patch `0016-Rename-Cmake-Library` has `.bak` extension, why not `.patch`?

**Comment by CastagnaIT** [comment]
always referred to `0016-Rename-Cmake-Library` patch is a diff without headers
seem wrong to me

**Comment by glennguy** [comment]
Thanks for picking up the sha256 - I forgot to do this, done now

Regarding patch 0016 - was just used in figuring out what I was doing wrong trying to get it to build, and again forgot to remove! 

Thanks for the review, ready for another look now

**Comment by bkuhls** [comment]
> Patches included (many thanks to @CastagnaIT for his hard work in preparing them) to bring the external version to the modified version that was previously bundled. Using the latest tagged version of bento4 (1.6.0-639) with an additional patch from master to support cmake install.

Hi,

from a [package maintainer](https://git.buildroot.net/buildroot/tree/DEVELOPERS#n343)  perspective I would like to ask if it is possible that these patches could be sent upstream for inclusion in future releases of bento4.

**Comment by glennguy** [comment]
@bkuhls - @CastagnaIT has this underway here https://github.com/axiomatic-systems/Bento4/issues/648

**Comment by glennguy** [comment]
@CastagnaIT can you please check again when you have time, I've addressed your issues. Thanks!

**Review by CastagnaIT — APPROVED** [review]
tried build&run and seem ok
i sent to you a message on slack to ask some thing about debugging

**Pull request merged**
