### PR TITLE
Translations update from Weblate

### PR DESCRIPTION
**Pull request by weblate**
Translations update from [Weblate](https://kodi.weblate.cloud/projects/kodi-add-ons-videoplayer-inputstream/inputstream-adaptive/) for Kodi add-ons: videoplayer inputstream/inputstream.adaptive.

Current translation status:

Weblate translation status

### CODE REVIEW

**Comment by gade01** [comment]
Do not merge this PR!

**Comment by phunkyfish** [comment]
> Do not merge this PR!

I merged your directory name change PR and approved the workflow. So once this is updated you should be able to proceed.

**Comment by gade01** [comment]
@phunkyfish 
Thanks a lot.

Actually this PR should be closed.
It contains the wrong language `in_hi`, which Weblate created when the component was added.
I have now removed that wrong language from Weblate as well.

So when we close this PR, I'll manually create a new one at Weblate.

**Comment by phunkyfish** [comment]
> @phunkyfish
> Thanks a lot.
> 
> Actually this PR should be closed.
> It contains the wrong language `in_hi`, which Weblate created when the component was added.
> I have now removed that wrong language from Weblate as well.
> 
> So when we close this PR, I'll manually create a new one at Weblate.

Done!

**Pull request closed without merging**
