### PR TITLE
added .gitattributes to avoid the issue with LE for patches and diffs.

### PR DESCRIPTION
**Pull request by afedchin**
see title.

### CODE REVIEW

**Comment by peak3d** [comment]
What does this PR do exactly? I like to see in diff if I have CRLF line endings because I remove them.
If this PR hides the line endings issues, it would not match to my working behaviour.

**Comment by afedchin** [comment]
This makes checkout diffs with LF ending on all platforms

**Comment by Rechi** [comment]
@afedchin the issue is that expat's CMakeLists.txt has windows line endings, but the patch has linux line endings.

**Comment by afedchin** [comment]
```
[ 14%] Performing patch step for 'expat'
patching file CMakeLists.txt
Assertion failed: p_base <= file_pos, file ../patch-2.5.9-src/pch.c, line 772

This application has requested the Runtime to terminate it in an unusual way.
Please contact the application's support team for more information.
[ 14%] Performing configure step for 'expat'
```
As I saw configuring is done well, expat build fails because path step fails.

**Comment by afedchin** [comment]
nvm, I got you

**Comment by afedchin** [comment]
I've upload expat archive with fixed CMakeLists.txt line endings

**Comment by Rechi** [comment]
> I've upload expat archive with fixed CMakeLists.txt line endings
If you want to upload a fixed version don't override the original file, have reverted it.

**Comment by Rechi** [comment]
Just check in the second patch with windows line endings, like it was done for the first one.

**Comment by afedchin** [comment]
@Rechi may be we should update the patch utility to avoid the similar issues in the future?  I have v2.7.5 installed with msys-git and it works well.

**Comment by Rechi** [comment]
If you can find a patch executable which isn't linked against `msys-2.0.dll` or similar shared libs, do it.

**Comment by afedchin** [comment]
What's wrong with shared libs?

**Comment by Rechi** [comment]
I would prefer a version without shared libs, but as long as you package all required libs it's fine for me.

**Pull request merged**
