### PR TITLE
[Leia] Use the full BaseUrl if it's a real url inside an AdaptationSet

### PR DESCRIPTION
**Pull request by michaelarnauts**
Backport of https://github.com/peak3d/inputstream.adaptive/pull/565

### CODE REVIEW

**Comment by michaelarnauts** [comment]
@peak3d Since the matrix-change had just been merged, can you also merge this backport? Thanks a lot!

**Comment by peak3d** [comment]
@michaelarnauts there are 2 more issues regarding url composing.
Let me figure them out, after that backport.....

**Comment by michaelarnauts** [comment]
@peak3d any update? I have two broken add-ons so I would love to have a release before the holidays...

**Comment by michaelarnauts** [comment]
Any progress? Something where I can help?

**Comment by MPParsley** [comment]
Hi @peak3d, any chance for a release with this?

**Comment by michaelarnauts** [comment]
@phunkyfish I didn't know a Leia release was happening. This is a simple bugfix that could have also been released.

**Comment by michaelarnauts** [comment]
O, never mind.it seems the commit made it into the release. Not sure how that happened 🙂

**Comment by phunkyfish** [comment]
> O, never mind.it seems the commit made it into the release. Not sure how that happened 🙂

@matthuisman added it 😉

**Comment by phunkyfish** [comment]
> @phunkyfish I didn't know a Leia release was happening. This is a simple bugfix that could have also been released.

That is the last Leia release

**Comment by matthuisman** [comment]
Yes. Snuck it in! This PR could now be closed :)

**Pull request closed without merging**
