### PR TITLE
[SmoothStreaming] Cleanups and fix loading of PlayReady header data

### PR DESCRIPTION
**Pull request by CastagnaIT**
## Description

Implement proper PlayReady header object data parsing
and some parser cleanups

The CharArrayParser has been taken from Kodi core

~I have not tested DRM protected stream yet, thats need to be tested on android,~ edit read comment below
just parsed header data to check if works

## Motivation and context

I was testing SmoothStreaming and i found that the header parsing was now broken
this because in the parser rework i changed from tinyxml2 to pugixml library
and i have removed this weird thing:
https://github.com/xbmc/inputstream.adaptive/blob/Nexus/src/parser/PRProtectionParser.cpp#L84-L86

after investigation i have found that old implementation was doing wrong things
PlayReady header object need to be parsed (something like mp4 data) by bytes
then fetch whole data its wrong and can lead to wrong data

## Types of change

- [x] **Bug fix** (non-breaking change which fixes an issue)
- [x] **Clean up** (non-breaking change which removes non-working, unmaintained functionality)
- [ ] **Improvement** (non-breaking change which improves existing functionality)
- [ ] **New feature** (non-breaking change which adds functionality)
- [ ] **Breaking change** (fix or feature that will cause existing functionality to change)
- [ ] **Cosmetic change** (non-breaking change that doesn't touch code)
- [ ] **None of the above** (please explain below)

## Checklist:

- [x] I have read the **[Contributing](https://github.com/xbmc/xbmc/blob/master/docs/CONTRIBUTING.md)** document
- [x] My code follows the **[Code Guidelines](https://github.com/xbmc/xbmc/blob/master/docs/CODE_GUIDELINES.md)** of this project 
- [ ] My change requires a change to the Wiki documentation
- [ ] I have updated the documentation accordingly

### CODE REVIEW

**Comment by CastagnaIT** [comment]
@glennguy i tested on shield following DRM sample stream

```
#KODIPROP:inputstream=inputstream.adaptive
#KODIPROP:inputstream.adaptive.manifest_type=ism
#KODIPROP:inputstream.adaptive.license_type=com.microsoft.playready
http://profficialsite.origin.mediaservices.windows.net/c51358ea-9a5e-4322-8951-897d640fdfd7/tearsofsteel_4k.ism/manifest
```
but there are a lot of errors
`AddOnLog: inputstream.adaptive: DecryptSampleData: Failed to cast AP4 decrypter to Adaptive`
https://paste.kodi.tv/ipikiwafel.kodi

any idea?
if require code change not related to this PR we can fix on a separate PR

**Comment by glennguy** [comment]
Did you get the issue in last comment sorted?

**Comment by CastagnaIT** [comment]
no just rebased PR

**Comment by glennguy** [comment]
No worries. Are these errors stopping playback?

**Comment by CastagnaIT** [comment]
yes playback is full broken

**Review by glennguy — APPROVED** [review]
All looks good, thanks!

**Comment by glennguy** [comment]
I think the issue relates to my changes in the single session PR, so this can be merged when you're ready and we find the issue separately.

Not really sure why this cast fails, maybe something else needed to be changed in wvdecrypter_android.cpp that I missed. Or maybe we're not getting the proper `WV_CencSingleSampleDecrypter` type created to begin with.

I will try to set up a debugging environment later in the week if we don't have any solid ideas

**Pull request merged**
