### PR TITLE
Hlskid

### PR DESCRIPTION
**Pull request by peak3d**
- Fix HLS widevine handling
- Introduce inputstream.adaptive.license_flags=force_secure_decoder
- add .clang-format
- implement vtt subtitles

### CODE REVIEW

**Comment by matthuisman** [comment]
This should fix Disney+ on Android and ARM devices.

Test builds here:
https://jenkins.kodi.tv/blue/organizations/jenkins/peak3d%2Finputstream.adaptive/detail/PR-417/1/artifacts

Will update this post shortly with my test results

UPDATE
Disney+ works great on my Android phone
Also tested all other Widevine & HLS add-ons and all OK.
Thinks safe to merge
Backport to Leia would also be nice if possible

Thank you!

**Comment by glennguy** [comment]
Reusing decrypter works great, switching variant streams is near instantaneous now!

**Comment by matthuisman** [comment]
please merge mr @peak3d before the angry mob of Android users tear down my door!
At least in master it will get into nightly android builds and keep them happy

**Comment by MastaG** [comment]
And please backport to Leia as well :-)
Thanks!

**Comment by matthuisman** [comment]
seems to be a few issues with latest update to this branch

1) Audio stops after a few seconds (5.1), and the video jumps back a few seconds 
    after you ffwd or seek ahead. Doesn't do it on 2.0
    If you just let it play from start - no issue
2) Subtitles are selectable but don't show (on all Disney+ content)
   Still improvement on what we had tho :)

**Comment by matthuisman** [comment]
@peak3d 
Audio issue completely fixed - thank you!
And subtitles a lot more reliable

Am I correct in thinking subs won't start for awhile (or at all) when changing subs or seeking during playback.
I assume this is when the seek to / current playing is say half way through a segment.
Kodi won't have downloaded the subs for current segment so will start them on next segment.
Anyway around that? Not a huge deal though.

To replicate - (Mandalorian episode 1)
start playback from start with any subtitles
Change subtitles (Sometimes does it with the language you start with as well.)
Seek to 15:00
Subs wont work again

**Comment by ghost** [comment]
Hi,

I want to know how do you fix the bug screen of Disney + on Kodi 18.6 on Android ?
Thanks.

**Comment by peak3d** [comment]
Changes merged into Matrix

**Comment by MastaG** [comment]
No backport to Leia?

**Comment by matthuisman** [comment]
He only committed 25 mins ago.
Give him a chance please

**Comment by MastaG** [comment]
Sorry Matt,

Didn't mean to be a dick.
I was just asking whether Leia is also going to get this improvement.
Could also be the case that no further development is going to happen for Leia.

**Comment by matthuisman** [comment]
he usually back-ports :)

**Pull request closed without merging**
