### PR TITLE
GR strings for 2.6.12

### PR DESCRIPTION
**Pull request by Twilight0**
GR strings for 2.6.12

### CODE REVIEW

**Comment by Twilight0** [comment]
Question: Is this the right branch to request the pull? Should I also request for Leia?

**Comment by phunkyfish** [comment]
We only update en_gb in the source. The rest is automated by transfix. I believe this is moving to weblate soon.

**Comment by phunkyfish** [comment]
I'm not sure where you should send any translations.

**Comment by phunkyfish** [comment]
Translations have moved to Weblate. Please follow the instructions here to sign up and contribute:

https://kodi.tv/article/switching-translations-to-weblate/

**Pull request closed without merging**
