### PR TITLE
[AdaptiveStream] On start stream prevent to stop subtitles stream

### LINKED ISSUE #1448: [K20/K21] MPD: "Cannot extract PSSH/KID" in subtitles shutdowns playback fully
## Bug report
All subtitles globally disabled in kodi.

But some of collection  IPTV streams fails to play, with PSSH/KID error in *subtitles* stream (see log below).
Also reproduceble in stable Kodi 20.

### Describe the bug

Here is a clear and concise description of what the problem is:

Log snipped contains general info:
```
ile::Open - <https://htv-rrs.mts.ru/PLTV/88888888/224/3221228154/3221228154.mpd> Effective URL is https://cache01-fed.spb.cdn.kion.ru/PLTV/88888888/224/3221228154/3221228154.mpd
og: inputstream.adaptive: Download finished: https://htv-rrs.mts.ru/PLTV/88888888/224/3221228154/3221228154.mpd (downloaded 9240 byte, speed 16135.00 byte/s)
og: inputstream.adaptive: Manifest saved to: /var/lib/kodi/.kodi/userdata/addon_data/inputstream.adaptive/manifests/manifest_1704312960.txt
og: inputstream.adaptive: Manifest successfully parsed (Periods: 1, Streams in first period: 3, Type: live)
og: inputstream.adaptive: New period, dispose sample decrypter and reinitialize
og: inputstream.adaptive: Entering encryption section
og: inputstream.adaptive: Initialize: CDM version: 4.10.2557.0
og: inputstream.adaptive: OnInitialized: CDM is initialized: true
og: inputstream.adaptive: Created AdaptiveStream [AS-0] with adaptation set ID: "3", stream type: subtitle
le::Open - <https://cache01-fed.spb.cdn.kion.ru/PLTV/88888888/224/3221228154/subtitles_init.m4i?hw_dash=1&servicetype=1&nil>
cquire - Created session to https://cache01-fed.spb.cdn.kion.ru
og: inputstream.adaptive: [AS-0] Download finished: https://cache01-fed.spb.cdn.kion.ru/PLTV/88888888/224/3221228154/subtitles_init.m4i?hw_dash=1&servicetype=1&nil (downloaded 751 byte, speed 4840.00 byte/s
og: inputstream.adaptive: License data: Cannot extract PSSH/KID data from the stream
og: inputstream.adaptive: Initializing stream with KID: d5e8f2aa3a56ecf09dde0088eaaf19b5
og: inputstream.adaptive: Initialize failed (SingleSampleDecrypter)
Player::OpenInputStream - error opening [pvr://channels/tv/%d0%92%d1%81%d0%b5%20%d0%ba%d0%b0%d0%bd%d0%b0%d0%bb%d1%8b@-1/1@pvr.iptvsimple_686388455.pvr]
Player::OnExit()
og: inputstream.adaptive: Close()
N:UnloadDll(/usr/lib/kodi/addons/inputstream.adaptive/inputstream.adaptive.so.21.4.1)
```

**For full log, see GIST files:
https://gist.github.com/helllamer/6ee0ce2bcca1eb2608752d7ce7352429**

File `iptv.m3u` contains two example WV-protected MPD streams
- first stream does not open in kodi, but works everythere, contains public-available content (but encrypted by this video-service) and subtitles
- second stream - just works without issues.
- example MPD (working and failing - see filenames)
- example of failing subtitles_init

Also, kodi 20 shows similar error
```
info <general>: AddOnLog: pvr.iptvsimple: pvr.iptvsimple - GetChannelStreamProperties - Live Stream URL: https://htv-rrs.mts.ru/PLTV/88888888/224/3221228154/3221228154.mpd
info <general>: Creating InputStream
info <general>: AddOnLog: inputstream.adaptive: [Repr. chooser] Resolution set: 1920x1080, max allowed: 1920x1080, Adjust refresh rate: 0
info <general>: AddOnLog: inputstream.adaptive: Successfully parsed manifest file (Periods: 1, Streams in first period: 3, Type: live)
error <general>: AddOnLog: inputstream.adaptive: Could not extract license from video stream (PSSH not found)
info <general>: ADDON: Dll Destroyed - InputStream Adaptive
 ```

## Expected Behavior
Here is a clear and concise description of what was expected to happen:

1. (crit) Stream https://htv-rrs.mts.ru/PLTV/88888888/224/3221228154/3221228154.mpd 
should just play, and subtitles error MUST NOT affect audio and video.
2. (maybe) Subtitles of stream 3221228154.mpd should be properly decrypted.
3. (feature-request) Also, if subtitles disabled in kodi settings, inputstream.adaptive must not do useless work for subtitles download, decryption and processing.

## Actual Behavior

1. Stream https://htv-rrs.mts.ru/PLTV/88888888/224/3221228154/3221228154.mpd
fails to decrypt subtitles PSSH/KID, and everything fails without any audio/video works.
2. Disabling/enabled subtitles does nothing in this situation.
3. For comparison, other MPD in playlist attached playbacks ok. 

## Possible Fix

`try { subtitlesInit() } catch { logger.error(); }`

### To Reproduce

1. Use provided GIST to collect basic information.
2. Possibly, use VPN inside Russia to access video-service.
4. Use playlist from GIST to reproduce the problem.
First stream will fail to play. Second stream -- will just work (for comparison).

### Debuglog

The debuglog can be found here:
https://gist.github.com/helllamer/6ee0ce2bcca1eb2608752d7ce7352429#file-kodi-log

### MPD/M3U8s/ISM

An example or copy of a manifest (or manifests for HLS - master and variants) can be found here:
https://gist.github.com/helllamer/6ee0ce2bcca1eb2608752d7ce7352429#file-iptv-m3u

### Your Environment
Used Operating system:

 - [ ] Android
 - [ ] iOS
 - [ ] tvOS
 - [x] Linux
 - [ ] OSX
 - [ ] Windows
 - [ ] Windows UWP

 - Operating system version/name: ArchLinux ARM AArch64
 - System: RaspberryPi 4
 - Kodi version: 21.x.64945.ae8850704e-2
 - inputstream.adaptive version: 21.4.1.Omega.r8.g2603755b-1 (today build)
 - glibc-widevine 2.35-5.3
 - widevine 4.10.2252.0
 - kodi-addon-pvr-iptvsimple-git r843.fc97f8d-1 (today)

*note: Once the issue is made we require you to update it with new information should that be required.
Team Kodi will consider your problem report however, we will not make any promises the problem will be solved.*

### PR DESCRIPTION
**Pull request by CastagnaIT**
## Description

Use case for mp4 isobmff segmented subtitles,
if you disable and re-enable subtitles while in playback (OSD) there is no guarantee of having segments available immediately here (next_segment), for live stream, you need to wait "insert live segments" and/or next manifest update
and this prevented getting the initialization segment

Indirectly this depends form PR #1505, just if you want test the attached sample stream

## Motivation and context

if you disable and re-enable subtitles while in playback (OSD) potentially can be broken
and following error is shown:

`2024-03-07 10:01:25.414 T:11904   error <general>: AddOnLog: inputstream.adaptive: ADP::CreateStreamReader: No MOOV atom in stream`

this happens because when you disable subs the stream is deleted with all related compents,
when you re-enable it, it is reinitialized from scratch again

fix #1448

## How has this been tested?

```
#KODIPROP:inputstream=inputstream.adaptive
#KODIPROP:inputstream.adaptive.manifest_type=mpd
#KODIPROP:inputstream.adaptive.license_type=com.widevine.alpha
#KODIPROP:inputstream.adaptive.license_key=https://htv-wv.mts.ru/?deviceId=MWFjMDU4NjktYjAxNC0zYmEyLWFmYjMtNjZmNzI3Nzg2NTgw||R{SSM}|
#EXTINF:-1 tvg-id="1",Encrypted Subtitles 1
https://htv-rrs.mts.ru/PLTV/88888888/224/3221228154/3221228154.mpd
```
## Types of change

- [x] **Bug fix** (non-breaking change which fixes an issue)
- [ ] **Clean up** (non-breaking change which removes non-working, unmaintained functionality)
- [ ] **Improvement** (non-breaking change which improves existing functionality)
- [ ] **New feature** (non-breaking change which adds functionality)
- [ ] **Breaking change** (fix or feature that will cause existing functionality to change)
- [ ] **Cosmetic change** (non-breaking change that doesn't touch code)
- [ ] **None of the above** (please explain below)

## Checklist:

- [ ] I have read the **[Contributing](https://github.com/xbmc/xbmc/blob/master/docs/CONTRIBUTING.md)** document
- [ ] My code follows the **[Code Guidelines](https://github.com/xbmc/xbmc/blob/master/docs/CODE_GUIDELINES.md)** of this project 
- [ ] My change requires a change to the Wiki documentation
- [ ] I have updated the documentation accordingly

### CODE REVIEW

**Comment by CastagnaIT** [comment]
@glennguy seem to work
but atm i cant test VOD stream with segmented subs my two samples are both broken...
let me know what do you think about this change if could be ok

**Comment by glennguy** [comment]
Hmmm I'm not sure. I can see how it would work with a single file. But not so clear to me what happens with segmented.

I think good test cases for multi segment subs would be:
* Disable and reenable subs while still in the same sub segment
* Disable subs, wait until play time has moved a couple of sub segments forward, reenable subs.
Maybe we can manually edit the akamai example to split sub segments further (only 2 or 3 per period at the moment...)

**Comment by CastagnaIT** [comment]
i have forgot to specify that you need subs as mp4 isobmff segments,
the akmai stream use plain "vtt" that is different
however i tested your points

> Disable and reenable subs while still in the same sub segment
> Disable subs, wait until play time has moved a couple of sub segments forward, reenable subs.

Both points works, they have same behaviour that i have recently fixed here:
https://github.com/xbmc/inputstream.adaptive/blob/df8b32db36cbf4e2e14441ebe533d547ebf3c947/src/common/AdaptiveStream.cpp#L655-L672
in short when you reenable subs from GUI OSD the `seek_time `is performed that find the approriate subtitle segment packet to be displayed on screen

this works in a immediate way for VOD,
for live streams instead subs will appear on screen a bit delayed due to buffering

we can try keep it, and see if there are some limited case that produce bad feedback from users
if so i will revert the PR

**Comment by CastagnaIT** [comment]
from what i can say, this seem to not cause side effects because there are no new segments immediately
so the "missing" updated currentPTSOffset_ isnt sent to kodi,
that will be sent when the new segment will be available with adaptiveStream ensureSegment method

maybe after merged the new rework PR opened, there is more chance to fix AdaptiveStream::start_stream in a better way
to avoid stop playback when there are no immediate segments also for audio/video side

**Review by glennguy — APPROVED** [review]

**Pull request merged**
