### PR TITLE
[HLS][Revert] share parameters between master / sub playlists

### PR DESCRIPTION
**Pull request by smf007**
Addresses the 403 errors noted in Issue #184.

### CODE REVIEW

**Comment by matthuisman** [comment]
This is interesting and something that could have been easily overlooked on a lot of 404 stream errors.

I confirmed Bitmovin and kodi ffmpeg both don't send the query string to the subplaylists or EXT-MEDIA.
If query strings are needed for them, the playlist should already have them in it

Test Matrix Builds Here:
https://jenkins.kodi.tv/blue/organizations/jenkins/peak3d%2Finputstream.adaptive/detail/PR-488/3/artifacts

**Comment by matthuisman** [comment]
maybe do a Leia backport PR as well.
Not sure if there will be new Leia IA version, but good to have it ready in case

**Comment by peak3d** [comment]
Even I'm quite sure that this will lead to regression for other streams, I'll let it in if the changes in AdaptiveTree are reverted.
I know that this is maybe currently dead code, but I'm sure that we need it later on.

**Review by peak3d — CHANGES_REQUESTED** [review]
Even I'm quite sure that this will lead to regression for other streams, I'll let it in if the changes in AdaptiveTree are reverted.
I know that this is maybe currently dead code, but I'm sure that we need it later on.

**Comment by smf007** [comment]
Thanks for the input Markus.  Updated as requested, and tested with my problematic CBC (Canadian Broadcast Corporation)  streams.

**Review by peak3d — APPROVED** [review]

**Pull request merged**
