### PR TITLE
[DRM][ClearKey] Add license url by DRM config, CK as DRM replacement

### LINKED ISSUE #811: Support for clearkey
is there any development for clearkey support soon?

### LINKED ISSUE #1637: [Feature request] Add support for fetching keys from Licence Server
### Describe the feature

I was trying to get a MPD stream working with clearkeys. 
I am using my own licence server to supply the clearkeys in the format `kid:key`. 
The keys are rotated after sometime, so I can't hardcode them in the m3u. 

I am using the following format to supply the keys:
`#KODIPROP:inputstream.adaptive.drm_legacy=org.w3.clearkey|http://localhost:5000/stream1`

But it fails with the error:
```License server URL not found```

### Motivation

The reason is that the keys keep changing so they can't be directly hard coded in the playlist. 

### Are you willing to contribute in development?

No

### Should a possible backport be considered?

No

### PR DESCRIPTION
**Pull request by CastagnaIT**
## Description

1) Add support to set license server url from property, example:
`#KODIPROP:inputstream.adaptive.drm_legacy=org.w3.clearkey|https://server/AcquireLicense`

2) Add support to pass http headers to license server request
3) Tested DASH Widevine stream, used with ClearKey as DRM replacement, as requested on #811 and #1637.
~The only limitation is that the manifest must provide the ContentProtection with `urn:mpeg:dash:mp4protection:2011` containing the `default_KID`~
4) Add support "ClearKey as DRM replacement" for HLS, but not tested since i havent found any stream
5) Add code to prevent a mixed misuse of DRM properties
6) Some code cleanups

## Motivation and context

closes #1637 
closes #811

## How has this been tested?

Tested MPD widevine protected by using ClearKey license server url provided by DRM config property, the tested MPD does not provide the ClearKey `ContentProtection` tag, as follow:
```
        <ContentProtection schemeIdUri="urn:mpeg:dash:mp4protection:2011" value="cenc" cenc:default_KID="**7B7D**-565C-4**3-B**F-**C33**654**" xmlns:cenc="urn:mpeg:cenc:2013"/>
        <ContentProtection schemeIdUri="urn:uuid:edef8ba9-79d6-4ace-a3c8-27dcd51d21ed">
          <cenc:pssh xmlns:cenc="urn:mpeg:cenc:2013">redacted</cenc:pssh>
        </ContentProtection>
        <ContentProtection schemeIdUri="urn:uuid:9a04f079-9840-4286-ab92-e65be0885f95" value="MSPR 2.0">
          <cenc:pssh xmlns:cenc="urn:mpeg:cenc:2013">redacted</cenc:pssh>
        </ContentProtection>
```
i cant publish here the test stream used

## Types of change

- [ ] **Bug fix** (non-breaking change which fixes an issue)
- [ ] **Clean up** (non-breaking change which removes non-working, unmaintained functionality)
- [x] **Improvement** (non-breaking change which improves existing functionality)
- [ ] **New feature** (non-breaking change which adds functionality)
- [ ] **Breaking change** (fix or feature that will cause existing functionality to change)
- [ ] **Cosmetic change** (non-breaking change that doesn't touch code)
- [ ] **None of the above** (please explain below)

## Checklist:

- [ ] I have read the **[Contributing](https://github.com/xbmc/xbmc/blob/master/docs/CONTRIBUTING.md)** document
- [ ] My code follows the **[Code Guidelines](https://github.com/xbmc/xbmc/blob/master/docs/CODE_GUIDELINES.md)** of this project 
- [ ] My change requires a change to the Wiki documentation
- [ ] I have updated the documentation accordingly

### CODE REVIEW

**Comment by Uukrull** [comment]
> ## Description
> 3. Tested DASH Widevine stream, used with ClearKey as DRM replacement, as requested on [Support for clearkey #811](https://github.com/xbmc/inputstream.adaptive/issues/811) and [[Feature request] Add support for fetching keys from Licence Server #1637](https://github.com/xbmc/inputstream.adaptive/issues/1637).
>    The only limitation is that the manifest must provide the ContentProtection with `urn:mpeg:dash:mp4protection:2011` containing the `default_KID`

What about extracting the default_KID from the urn:uuid:edef8ba9-79d6-4ace-a3c8-27dcd51d21ed PSSH if the default_KID doesn't exist?

**Comment by CastagnaIT** [comment]
> > ## Description
> > 
> > 3. Tested DASH Widevine stream, used with ClearKey as DRM replacement, as requested on [Support for clearkey #811](https://github.com/xbmc/inputstream.adaptive/issues/811) and [[Feature request] Add support for fetching keys from Licence Server #1637](https://github.com/xbmc/inputstream.adaptive/issues/1637).
> >    The only limitation is that the manifest must provide the ContentProtection with `urn:mpeg:dash:mp4protection:2011` containing the `default_KID`
> 
> What about extracting the default_KID from the urn:uuid:edef8ba9-79d6-4ace-a3c8-27dcd51d21ed PSSH if the default_KID doesn't exist?

iirc dash specs say `default_KID` should be placed on `urn:mpeg:dash:mp4protection:2011` scheme, if not exists it must be extracted from the mp4box, so services that place default_KID e.g. on urn:uuid:edef8ba9-79d6-4ace-a3c8-27dcd51d21ed scheme, are not conform to dash standards

an improvement would be when not found extract it from the mp4box, but this is a change that i want left after the DRM config rework

to do what you propose currently its needed add a workaround that in theory can be avoided after the rework
so is the reason why i havent add it on the code changes, but i will try take a look

**Comment by moszkowski97** [comment]
I've tried some live streams and it works nicely, thanks a lot.
For some reason if the manifest needs authorization headers, it doesn't work and throws 403 in the logs, ignoring inputstream.adaptive.stream_headers.
If i add the headers next to the manifest url, like this: url.mpd|header=token , it works for the first request of the manifest, but the subsequent ones it gives 403 again.

**Comment by CastagnaIT** [comment]
@moszkowski97 your problems are because you are using wrong ISA properties and wrong url pipe "|" along the URL is not supported on ISA and not specified on Wiki, i suggest you for full read the Wiki integration page and recheck what you are doing,
if after this you still have problems, open a new Issue thread and dont report to the development PR's

**Comment by alannl** [comment]
@CastagnaIT 
A HLS you can test with, please redact this comment after reading.
f70b7d35209b3b1aa52da275f085723b:98c1069b7749735487c315a86cdea55e
http://wp1-vxtoken-anp-g05060506-hzn-nl.t1.prd.dyncdn.dmdsdp.com/live/disk1/NL_000001_019401/go-hls-fhd-hevc/NL_000001_019401.m3u8

**Comment by CastagnaIT** [comment]
@alannl thanks i have saved it, your comment deleted as requested, to avoid keep comment history
i will take a look on next days

**Comment by basilgello** [comment]
@CastagnaIT FYI, via actibity API all "deleted" comments (even from "deleted" accounts!) are visible just fine :)

**Comment by alannl** [comment]
@CastagnaIT 
Were you able to get the video link to play? It does work with IS, Widevine and proxy.
Clearkey with altered manifest tru proxy so that KID is detected, gives this error, if this check is ignored, maybe it will work with clearkey:
ClearKeyDecrypter::CreateSingleSampleDecrypter: Cannot initialize ClearKey DRM. Only "cenc" encryption supported.
Hope it's ok to address it in this thread

**Comment by CastagnaIT** [comment]
> Hope it's ok to address it in this thread

no, dont use development PR's for discussions
i verified your video but is done with cbcs encryption, and so cannot be played
this encryption is not supported atm, maybe in future

**Comment by alannl** [comment]
But the interesting thing is that this exact stream works fine in Kodi using WV, maybe you can get it to work with CC:
AddOnLog: inputstream.adaptive: Entering encryption section
AddOnLog: inputstream.adaptive: Initializing stream with KID: f[...]
AddOnLog: inputstream.adaptive: CWVCencSingleSampleDecrypter::GetCapabilities: Single decrypt possible

Feel free to remove my comments to clean up, I got my point across.

**Pull request merged**
