### PR TITLE
Add Hebrew translation [he_IL]

### PR DESCRIPTION
**Pull request by haggaie**

### CODE REVIEW

**Comment by CastagnaIT** [comment]
This need to be aligned to the new changes,
please update your file by comparing english language file

**Comment by haggaie** [comment]
> This need to be aligned to the new changes,
> please update your file by comparing english language file

I thought it is completely aligned. I copied the [English file](https://github.com/peak3d/inputstream.adaptive/blob/089c7c99eef3398da4786834535f639b0439f0f9/inputstream.adaptive/resources/language/resource.language.en_gb/strings.po) before I started the translation.

Or did you mean I was working on the wrong branch? Should I submit the pull request to Matrix first?

**Comment by CastagnaIT** [comment]
is that right now we are making several changes
I have now seen that the changes to the language for Leia has not yet been merged
so you can currently prepare the Matrix part
and leave Leia temporary on hold

**Review by peak3d — APPROVED** [review]

**Comment by peak3d** [comment]
Thx @haggaie !

**Comment by peak3d** [comment]
> is that right now we are making several changes
> I have now seen that the changes to the language for Leia has not yet been merged
> so you can currently prepare the Matrix part
> and leave Leia temporary on hold

@CastagnaIT which PR ?

**Comment by CastagnaIT** [comment]
@peak3d you have merged a incomplete pr
This have need to rebase before merge
Now is needed fix the language separately
Have wrong ids

**Comment by peak3d** [comment]
reverted @CastagnaIT

**Comment by CastagnaIT** [comment]
@haggaie please make new PR's with updated language

**Pull request merged**
