### PR TITLE
Handle AES PKCS7 padding [Matrix]

### PR DESCRIPTION
**Pull request by TermeHansen**
backport of #998

### CODE REVIEW

**Comment by TermeHansen** [comment]
@glennguy or @CastagnaIT is that CI jenkins failure something that happens ones in a while or something I did wrong for this PR?

**Comment by glennguy** [comment]
Nah it must be something on the servers that do the build, nothing to do with the code changes.

**Comment by CastagnaIT** [comment]
@TermeHansen a hint for the future, the PR description it is more important write

"backport of #PR_Number"
or
"partial backport of #PR_Number"

if it is appropriate specify use cases tested then can be included after that line
however thanks for this

**Comment by TermeHansen** [comment]
> @TermeHansen a hint for the future, the PR description it is more important write
> 
> "backport of #PR_Number" or "partial backport of #PR_Number"
> 
> if it is appropriate specify use cases tested then can be included after that line however thanks for this

Thanks for the inputs. On that note isn't it possible to squash commit when merging PRs in, so it doesn't matter so much how many commits are in the branch/PR?

Anyhow, I hope this soon makes it into a 19.0.6 release for my users to get.

... and please reach out to me if you would like some extra testing of things now that I have everything set up.

**Comment by CastagnaIT** [comment]
> Thanks for the inputs. On that note isn't it possible to squash commit when merging PRs in, so it doesn't matter so much how many commits are in the branch/PR?

squashing commits for a merge will produce garbage in the branch history
therefore in kodi repositories we use the rule to keep the title and description and commits consistent with the content
this will make future backward searches or reverts less complicated and more clear

**Comment by glennguy** [comment]
Before we can do a release the issue with the build servers must be fixed, I'll ask around

**Comment by TermeHansen** [comment]
@glennguy seems like the issue on Jenkins is resolved...

**Review by glennguy — APPROVED** [review]
Thanks @TermeHansen

**Pull request merged**
