### PR TITLE
[Leia] Backports

### PR DESCRIPTION
**Pull request by matthuisman**
**TEST BUILDS**
Windows x86_64
https://jenkins.kodi.tv/job/xbmc/job/inputstream.adaptive/job/PR-711/17/artifact/cmake/addons/build/zips/inputstream.adaptive+windows-x86_64/inputstream.adaptive-2.4.8.zip

Android ARM7
https://jenkins.kodi.tv/job/xbmc/job/inputstream.adaptive/job/PR-711/17/artifact/cmake/addons/build/zips/inputstream.adaptive+android-armv7/inputstream.adaptive-2.4.8.zip

Android AARCH64
https://jenkins.kodi.tv/job/xbmc/job/inputstream.adaptive/job/PR-711/17/artifact/cmake/addons/build/zips/inputstream.adaptive+android-aarch64/inputstream.adaptive-2.4.8.zip

OSX x86_64
https://jenkins.kodi.tv/job/xbmc/job/inputstream.adaptive/job/PR-711/17/artifact/cmake/addons/build/zips/inputstream.adaptive+osx-x86_64/inputstream.adaptive-2.4.8.zip

Linux x86_64
https://f.mjh.nz/ia/PR711_15-linux-x86_64.zip

Linux ARM7 (Raspberry Pi, Odroid etc)
https://f.mjh.nz/ia/PR711_15-linux-armv7.zip

**CHANGES**
- https://github.com/xbmc/inputstream.adaptive/pull/630 (already merged)
- https://github.com/xbmc/inputstream.adaptive/pull/589
- https://github.com/xbmc/inputstream.adaptive/pull/684
- https://github.com/xbmc/inputstream.adaptive/pull/665
- https://github.com/xbmc/inputstream.adaptive/pull/645
- https://github.com/xbmc/inputstream.adaptive/pull/709
- https://github.com/xbmc/inputstream.adaptive/pull/668
- https://github.com/xbmc/inputstream.adaptive/pull/708
- https://github.com/xbmc/inputstream.adaptive/pull/477
- https://github.com/xbmc/inputstream.adaptive/pull/685
- https://github.com/xbmc/inputstream.adaptive/pull/729

**NOTES**
We can have a nice long window (eg. 3-4 weeks) to test before pushing it.

Commit for version bump also removes the "to do" for Multi-period support as Leia has supported that for a while now.
and removes the old changelog.txt (not used) and updates the credits in the readme

### CODE REVIEW

**Comment by glennguy** [comment]
Looks good except it might be best to omit the default update_parameter to full one as that changes default behaviour - won't help existing add-ons that work already in Leia anyway.

I'll do a branch with the disco-seq changes and you can cherry pick from there

**Comment by glennguy** [comment]
@matthuisman cherry pick the 2 commits from here: https://github.com/glennguy/inputstream.adaptive/tree/Leia-disco-seq
I have not tested myself, but it should be identical to the changes made in IAT. TravisCI builds pass.

**Comment by matthuisman** [comment]
> Looks good except it might be best to omit the default update_parameter to full one as that changes default behaviour - won't help existing add-ons that work already in Leia anyway.

It would be nice to have this. Just means if someone writes an addon for matrix and then tries to make it work on Leia too, they will get same behavior. It doesn't break anything but does make behavior consistent across branches. Also stops the bug issues for any new devs making Leia add-ons and their stream fails after a few seconds. 

Happy to remove but just think it  would more people out and maybe save us some time on new issues?

**Comment by matthuisman** [comment]
OK, pretty sure that's everything!
Test builds are up.
Also built for Linux x86_64 and armv7

Ive tested myself and everything seems to work good.
License renewal confirmed working. X-Disc seems good 

Quite a few commits wouldn't merge in nicely due to conflicts.
So lots are done manually (i find the conflict view harder than manually bring in the code from diff)
I also squashed down any multiple commits.
Doing this lost the original author of the commits.

I can manually rebase and go through each commit fixing the author if wanted?

@glennguy maybe you want to check X-Disc playback seems good to you as well
and the seeking issue is ok (i had to manually merge that)

**Comment by glennguy** [comment]
> Happy to remove but just think it would more people out and maybe save us some time on new issues?

It should be ok, no complaints with being in Matrix for the last 2 releases.

> I also squashed down any multiple commits.
Doing this lost the original author of the commits.

tbh at the very least we need to retain the original authors. As for merge conflicts I'm using GitHub Desktop most of the time and the default Atom editor is very nice for selecting which to use for each conflict.

**Comment by matthuisman** [comment]
@glennguy 
Fixed the authors :)
Yeh, VS code does a pretty decent conflict view too. I just don't trust it. haha
some changes where actually needed as well, eg. in your seek PR, I had to change STREAM_TIME_BASE  to DVD_TIME_BASE.
It must have been renamed in Matrix branche at some point.

**Comment by phunkyfish** [comment]
> @glennguy
> Fixed the authors :)
> Yeh, VS code does a pretty decent conflict view too. I just don't trust it. haha
> some changes where actually needed as well, eg. in your seek PR, I had to change STREAM_TIME_BASE to DVD_TIME_BASE.
> It must have been renamed in Matrix branche at some point.

Yes, all that was changed in Matrix.

**Comment by glennguy** [comment]
This will need #729 once finalised/merged as well

**Comment by matthuisman** [comment]
Yup! will wait for that to get merged then add to backports

**Review by phunkyfish — APPROVED** [review]
LGTM

**Review by glennguy — APPROVED** [review]

**Pull request merged**
