### PR TITLE
[Deps] Reverted recents bento4 commits

### LINKED ISSUE #1617: [21.5.0] Disney+, MAX (& others?) freeze on 5.1 audio
### Describe the problem

https://forum.kodi.tv/showthread.php?tid=353316&pid=3205609#pid3205609

I didn't change anything in my setup. It happens both on my Shield and my Philips TV with Google TV 12. I tried downgrading to InputStream:Adaptive 21.4.10 (because that was the only thing that was updated the last few days, except Sly Guy Common which was also updated), but that didn't work.

The audio track does show up as selected in the OSD, but Kodi's debug info screen does not show any audio playing.

Also, local media files with DD+ 6-channel tracks still work fine.

Any clues?

EDIT

Sorry, I used the wrong ZIP file to downgrade IS:A. After doing a proper downgrade to 21.4.10, 6-channel DD+ tracks started to work again.

Disney+ = HLS with Widevine
MAX = Dash with Widevine

### Possible fix

_No response_

### Steps to reproduce

_No response_

### Debug log

(none yet)

### Stream manifest file(s)

_No response_

### Additional info

_No response_

### Operating system(s)

Android

### Operating system version(s)

_No response_

### InputStream Adaptive version(s)

21.5.0

### Kodi version(s)

21

### PR DESCRIPTION
**Pull request by CastagnaIT**
## Description

The last commits in to bento4 upstream master branch
have introduced a bug that seem to corrupt the audio packet data
causing kodi audio parser not to recognise eac3 audio packages (dd+ / atmos)

i have done a new bento4 branch reverting all new upstream commits,
keeping only 3 new commits: 1 CPP20 fix, other 2 are parents of the latter this to avoid unofficial code changes

NOTE: i will finish/fix the temporary commit tomorrow

## Motivation and context

fix #1617

## Types of change

- [x] **Bug fix** (non-breaking change which fixes an issue)
- [ ] **Clean up** (non-breaking change which removes non-working, unmaintained functionality)
- [ ] **Improvement** (non-breaking change which improves existing functionality)
- [ ] **New feature** (non-breaking change which adds functionality)
- [ ] **Breaking change** (fix or feature that will cause existing functionality to change)
- [ ] **Cosmetic change** (non-breaking change that doesn't touch code)
- [ ] **None of the above** (please explain below)

## Checklist:

- [ ] I have read the **[Contributing](https://github.com/xbmc/xbmc/blob/master/docs/CONTRIBUTING.md)** document
- [ ] My code follows the **[Code Guidelines](https://github.com/xbmc/xbmc/blob/master/docs/CODE_GUIDELINES.md)** of this project 
- [ ] My change requires a change to the Wiki documentation
- [ ] I have updated the documentation accordingly

### CODE REVIEW

**Comment by matthuisman** [comment]
watching :)

**Comment by CastagnaIT** [comment]
tested last CI build here on android and DD+ seem to works now
can you confirm?

if so there is some shit of bug on bento library, last commits
https://github.com/axiomatic-systems/Bento4/compare/v1.6.0-641...master
initially i tried to revert only https://github.com/axiomatic-systems/Bento4/commit/66e29226d27784e39cddc7ff61240087f3618e88 but still not working

**Comment by matthuisman** [comment]
testing now :)

**Comment by matthuisman** [comment]
Max working great with this version :) on 5.1 and atmos and 2.0

**Comment by CastagnaIT** [comment]
shit ok, i will open an Issue on bento4 and i push a new reverted bento branch
i am not going to build and test every single commit of bento4...

**Comment by Ronny-nerd** [comment]
Thanks for this new PR-1618 CastagnaIT ...no more sound codec problems.

**Pull request merged**
