### PR TITLE
Bento4 update

### PR DESCRIPTION
**Pull request by glennguy**
Hi @peak3d

I've brought all the files up to date with Bento 4 commit 158655e.

All of the changes that I could find between the initial commit of Bento4 in IA and now have been re-added. Tested on several streams, widevine/dash/hls

I've spread across several commits to 'show the working' to make it clearer, I'm hoping you'll squash if this is suitable for merge

Thanks for your time

Glenn

### CODE REVIEW

**Comment by Maven85** [comment]
With these changes, it will not be possible to fast-forward videos from the Netflix addon.

If you start a video and try to fast-forward it, the video will stop playing.

**Comment by dagwieers** [comment]
cc @CastagnaIT

**Comment by glennguy** [comment]
Thanks for the heads up @Maven85 

I don't have access to a netflix account atm, have you seen this behaviour in any other streams?

**Comment by Maven85** [comment]
I tested a couple of addons:

Netflix -> playback stops while fast forwarding
Amazon VOD -> playback stops while fast forwarding
SkyGo (PlayReady & Widevine) -> Kodi crashes on startup

My device: Nvidia Shield TV (2015)

Edit: Same behaviour with my Win10 PC

**Pull request closed without merging**
