### PR TITLE
Recursively search for decrypters

### PR DESCRIPTION
**Pull request by GTechAlpha**
Does not find libssd_wv in the lib sub-directory of addon directory.

### CODE REVIEW

**Comment by MilhouseVH** [comment]
Why not just move `libssd_wv` into the root where it is now expected (since about version 2.0.16), and ensure the addon is being packaged using the correct locations? There's no need to search recursively - if `libssd_wv` is where it's expected to be it either doesn't exist, or the addon isn't packaged correctly.

**Comment by GTechAlpha** [comment]
~~LibreELEC package still places it in lib sub-directory~~.

I see that you updated the package - thanks for that. I think recursively searching would still be beneficial for possible future inconsistencies.

**Comment by MilhouseVH** [comment]
I can see why you'd suggest that, but it's unnecessary complexity to resolve what would be a packaging error.

If you were to upgrade to the latest version of this addon, then `libssd_wv` should be found in two possible locations (`/usr/lib` on Linux, or the addon root) and nowhere else, in which case searching recursively is unnecessary complexity and overhead.

**Comment by GTechAlpha** [comment]
The code is fairly simple. If the lib is found in one of the default search locations, the search stops, taking no extra time. If not, the search attempts to find it recursively.

**Comment by peak3d** [comment]
Sorry, I see no reason for this and it could break things for users who store old libssd_wv's in a temp child folder

**Comment by GTechAlpha** [comment]
That's fine. For the record, an old lib would only be used if a lib was not first found one of the default search directories.

**Pull request closed without merging**
