### PR TITLE
Bump to v2.6.15

### PR DESCRIPTION
**Pull request by glennguy**
This is a call out to all users and stakeholders to test the incoming Matrix inputstream.adaptive v2.6.15 with your add-on(s) and report back.

You can find various v2.6.15 builds at:
* [Most platforms (Android, iOS, macOS and Windows)](https://jenkins.kodi.tv/blue/organizations/jenkins/xbmc%2Finputstream.adaptive/detail/PR-683/1/artifacts)
* Linux platforms can be compiled from source - please see [here (incomplete)](https://github.com/xbmc/inputstream.adaptive/wiki/How-to-build). When building from source be sure to checkout this commit https://github.com/xbmc/inputstream.adaptive/commit/b437272f5d85e2de072df897aed3c82115a3c40c

If you want to do extensive testing with your add-on(s), you can find a list of tasks to complete to test the behaviour: https://github.com/xbmc/inputstream.adaptive/wiki/Test-plan

And you can report back success or failure at the Wiki at: https://github.com/xbmc/inputstream.adaptive/wiki/Test-results

The main features introduced in this release are:
* Automatically retrying widevine streams that fail on L1 provisioning with an attempt at L3. This stops 'blank screen' for users that have the typical 'cheap' Android box with 'fake' L1, and they instead get to at least watch the SD L3 stream.
* Secure decoder will automatically be tried on devices with secure decoders/L1 capabilities rather than add-ons having to 'force' the secure decoder. Old behaviour is still available through an IA expert setting.

There are reports that the secure decoder is causing stuttering where non-secure decoding did not. Please report if you encounter this.

### CODE REVIEW

**Comment by glennguy** [comment]
@dagwieers @michaelarnauts @CastagnaIT @Testato @matthuisman 
please report here or on wiki if there's any issues, and include any others you think should be testing. Looking to merge in a few days.

**Comment by basrieter** [comment]
I tried and have some issues with AC3 (5.1) audio streams. But that also seems to be with version v2.6.14. I tried to play https://www.svtplay.se/morden-vid-kustvagen via Retrospect (SVT), but it is Geo bound to Sweden. It has multiple audio streams, but only the 2.0 streams work.

Other channels I tried seem fine. I checked MPD, MPD+DRM and HLS streams.

**Comment by CastagnaIT** [comment]
Tried netfx on my old L3 android smartphone a/v works as usual

**Comment by Testato** [comment]
Samsung S9+ (L1 device): Now the video is not blank, but it have stuttering, if i change the setting in the Expert section the video return to blank. (i removed the force secure decoder from LA7 plugin)

Nokia 3.4 (L1 device, at least by DRM info app): Video is stuttering by default and also by Expert old behaviour

Dooge S88Pro (L3 device): Video is ok, no stuttering

This tests is ok for me, because by the old IA version the Samsung was completely blank and the Nokia was stuttering.
The difference on Nokia is that using the secure decoder is worst that not using it, but there is stuttering in all cases, so this is not important because it is not acceptable the stuttering on new version but also is not acceptable in the old version.

So for me you can Bump to v2.6.15

(p.s. all test done by updated LA7 plugin version https://github.com/luivit/plugin.video.rivedila7/archive/refs/heads/master.zip)

**Comment by matthuisman** [comment]
all ok for me on various add-ons / test streams
no regressions

**Review by matthuisman — APPROVED** [review]
all ok for me on various add-ons / test streams
no regressions

**Pull request merged**
