### PR TITLE
[HLS] set pssh media type for widevine

### PR DESCRIPTION
**Pull request by glennguy**
Fixes crashing when playing hls streams with encrypted video AND audio with the same PSSH

Was not included in #395 as the workflow with EXT-X-SESSION-KEY was causing an extra psshset to be added -> crash when switching streams

### CODE REVIEW

**Comment by peak3d** [comment]
Sorry, this PR must be done again. Pls. make sure that you squash your commits into one, if you have cosmetic and changes, pls. provide 2 PR's, each with one commit as long there is no reason to split.

**Comment by glennguy** [comment]
@Peak3d I think your comment was not intended for this PR? This is just one commit, one change.
Edit: did not notice force pushing sorry

**Comment by matthuisman** [comment]
@glennguy 
Peak3d re-wrote the commit history for this branch (force-push)
So your branch is now conflicting.
You can see this under commits or files changed for this PR.
It has 3 he originally made that now exist in your PR as they no longer exist in this branch.

I had to checkout his branch and then make the changes again and push new PR.

Actually, that code your commit was for has now changed (so maybe already fixed)
https://github.com/peak3d/inputstream.adaptive/blob/hlskid/src/parser/HLSTree.cpp#L604
&
https://github.com/peak3d/inputstream.adaptive/blob/hlskid/src/parser/HLSTree.cpp#L627

But maybe this has something to do with my new issue of audio stopping after fw or seeking

**Comment by glennguy** [comment]
Ah ok I see, will do

**Comment by matthuisman** [comment]
@glennguy 
Just tried and that issue with crashing is still present with the new changes
And also another bug now present (see below)
https://github.com/peak3d/inputstream.adaptive/pull/417#issuecomment-615510224

Used the build from here:
https://jenkins.kodi.tv/blue/organizations/jenkins/peak3d%2Finputstream.adaptive/detail/PR-426/1/artifacts

Thats peaks latest branch with the fix for not erroring on SAMPLE-AES
Playing Apple TV with media = all - crashes

**Comment by glennguy** [comment]
Perhaps since there's a bit of force pushing going on we should wait for hlskid to be merged into matrix then submit based off matrix?

@peak3d would this be your preference?

**Comment by peak3d** [comment]
Yes. pls. wait until hlskid is finished

**Pull request closed without merging**
