### PR TITLE
only set overallSeconds for non-subtitle playlists

### LINKED ISSUE #1054: HLS - Wrong duration calculated if bad/short subtitle subplaylist
master
```
#EXTM3U
#EXT-X-MEDIA:TYPE=SUBTITLES,GROUP-ID="subs",NAME="English",URI="subtitles.m3u8",LANGUAGE="en"
#EXT-X-STREAM-INF:PROGRAM-ID=1,BANDWIDTH=360448,RESOLUTION=426x240,CODECS="avc1.42001e,mp4a.40.2",SUBTITLES="subs"
media.m3u8
```
subtitles.m3u8
```
#EXTM3U
#EXT-X-VERSION:3
#EXT-X-TARGETDURATION:10
#EXTINF:10.008778,
sub_en_0.vtt
#EXTINF:10.008778,
sub_en_0.vtt
#EXT-X-ENDLIST
```
media.m3u8
```
#EXTM3U
#EXT-X-VERSION:3
#EXT-X-TARGETDURATION:10
#EXT-X-MEDIA-SEQUENCE:0
#EXTINF:10.000000,
1.mp4
#EXTINF:10.000000,
2.mp4
#EXTINF:10.000000,
3.mp4
#EXTINF:10.000000,
........
#EXT-X-ENDLIST
```

Kodi will show duration as 20secs (duration of subtitles.m3u8) instead of 16mins (duration of media.m3u8)
Changing IA to Video only fixes the duration as it ignores the subtitles.
FFMPEG also shows the correct duration

IA version: 19.0.7
Kodi version: 19.4
OS: Windows X64

screenshot00022

screenshot00023

### PR DESCRIPTION
**Pull request by matthuisman**
Fixes: https://github.com/xbmc/inputstream.adaptive/issues/1054

### CODE REVIEW

**Comment by matthuisman** [comment]
Wasn't sure if we should also not set periods_[discont_count]->duration

**Comment by glennguy** [comment]
Yes sorry I was going to comment - I think that's correct, we shouldn't be setting the period duration either. Also check further up in the ext-disco tag section

**Comment by matthuisman** [comment]
What about the rep->flags_?

**Comment by glennguy** [comment]
Still need to set that, otherwise the playlist will redownload everytime you switch to it on VOD

**Comment by matthuisman** [comment]
changed made, hopefully ok now :) tested with a few HLS and the troublesome stream and worked ok

**Review by glennguy — APPROVED** [review]
Thanks @matthuisman!

**Pull request merged**
