### PR TITLE
CInputStreamAdaptive: use std::map for m_IncludedStreams

### PR DESCRIPTION
**Pull request by lrusak**
I'm not sure why this was an array but it made no sense because the index was an enum

## Types of change

- [x] **Bug fix** (non-breaking change which fixes an issue)
- [x] **Clean up** (non-breaking change which removes non-working, unmaintained functionality)
- [ ] **Improvement** (non-breaking change which improves existing functionality)
- [ ] **New feature** (non-breaking change which adds functionality)
- [ ] **Breaking change** (fix or feature that will cause existing functionality to change)
- [ ] **Cosmetic change** (non-breaking change that doesn't touch code)
- [ ] **None of the above** (please explain below)

## Checklist:

- [ ] I have read the **[Contributing](https://github.com/xbmc/xbmc/blob/master/docs/CONTRIBUTING.md)** document
- [ ] My code follows the **[Code Guidelines](https://github.com/xbmc/xbmc/blob/master/docs/CODE_GUIDELINES.md)** of this project 
- [ ] My change requires a change to the Wiki documentation
- [ ] I have updated the documentation accordingly

### CODE REVIEW

**Comment by glennguy** [comment]
> I'm not sure why this was an array

We have no idea either unfortunately, but thank you for the improvement in readability.

**Review by glennguy — APPROVED** [review]

**Comment by glennguy** [comment]
As a note, this needs to be reworked as there's a limitation on 1 of each type of stream being 'included streams'. I've seen examples of .ts files that have 1 video, 3 audio and 3 subtitles streams. In this scenario last one in wins. I don't think it would be a straight forward task though.

**Comment by CastagnaIT** [comment]
seem have sense but i havent a sample to test it

**Comment by lrusak** [comment]
Merge?

**Comment by CastagnaIT** [comment]
it would be appropriate to do at least one test
but atm i dont have a sample stream for this use case, does anyone have one?

**Comment by glennguy** [comment]
The SBS Akamai sample stream is an example of this - tested working fine here :)

**Pull request merged**
