### PR TITLE
[Android] remove old ndk as not used

### PR DESCRIPTION
**Pull request by matthuisman**
remove wvdecrypter_android.cpp and CMakeLists.txt.ndk

rename wvdecrypter_android_jni.cpp to wvdecrypter_android.cpp
update CMakeLists.txt

Pretty sure we dont use ndk anymore as kodi was moved to jni

### CODE REVIEW

**Comment by glennguy** [comment]
Is there a way you can do this in git so that it will show as the file getting renamed? Maybe it would work across 2 commits? If not maybe just better to delete wvdecrypter_android and not rename wvdecrypter_android_jni.

I'm thinking about being able to use blame and history, that's all.

**Comment by matthuisman** [comment]
Haha. I had the same thought. I then did over two commits but when making the pull request, it showed as the same. But now I think that's because the pr window shows the changes all together! I'll try again.

**Comment by matthuisman** [comment]
@glennguy 
looks better now over 2 commits - thank you

**Comment by matthuisman** [comment]
@glennguy 
this also good to go for Nexus

**Review by glennguy — APPROVED** [review]
LGTM

**Review by phunkyfish — APPROVED** [review]

**Comment by matthuisman** [comment]
argh conflicts again... i'll fix
then can we get it in?

**Comment by matthuisman** [comment]
@glennguy  ready now :)

**Pull request merged**
