### PR TITLE
[decrypters] Various cleanups to interface

### PR DESCRIPTION
**Pull request by CastagnaIT**
## Description

1) Some cleanups to use the new service broker
2) The session m_profilePath is the path on user folder of the addon, that can be obtained also by using `UTILS::FILESYS::GetAddonUserPath`, this was used to set the decrypter SetProfilePath that was performing a manual path string shrinks to obtain the same path of the libraryPath...its not clear why there is this round of code apparently for nothing...all that code now has been removed
3) the "widevine" folder created under "cdm" folder used by cdm to store persistent data has been now moved to the addon user folder:
`..\data\userdata\addon_data\inputstream.adaptive\widevine`
I thought that if there are multiple kodi profiles, this will keep the cdm persistent data separate per kodi profile used, where previously it was not

## Motivation and context

long postponed cleaning
## Types of change

- [ ] **Bug fix** (non-breaking change which fixes an issue)
- [x] **Clean up** (non-breaking change which removes non-working, unmaintained functionality)
- [ ] **Improvement** (non-breaking change which improves existing functionality)
- [ ] **New feature** (non-breaking change which adds functionality)
- [ ] **Breaking change** (fix or feature that will cause existing functionality to change)
- [ ] **Cosmetic change** (non-breaking change that doesn't touch code)
- [ ] **None of the above** (please explain below)

## Checklist:

- [ ] I have read the **[Contributing](https://github.com/xbmc/xbmc/blob/master/docs/CONTRIBUTING.md)** document
- [ ] My code follows the **[Code Guidelines](https://github.com/xbmc/xbmc/blob/master/docs/CODE_GUIDELINES.md)** of this project 
- [ ] My change requires a change to the Wiki documentation
- [ ] I have updated the documentation accordingly

### CODE REVIEW

**Comment by CastagnaIT** [comment]
@glennguy have you a chance to do a fast test under linux (not android)? just to be sure that that there is no unexpected regressions with paths

**Comment by glennguy** [comment]
Sure! I've done a simple test on a widevine video with the debug options turned on
Manifest files turn up in the addon_data location:
image

However the license debug files are still ending up in the CDM folder:
image

Btw this is using existing settings from my previous installation (21 alpha ~April 2023)

**Comment by CastagnaIT** [comment]
thank you its ok

**Review by glennguy — APPROVED** [review]
👍

**Pull request merged**
