### PR TITLE
[workflows] Removed char replaces on changelog and release action

### PR DESCRIPTION
**Pull request by CastagnaIT**
## Description

I assume that this is not needed anymore since there is garbage on the release page
immagine

## Types of change

- [x] **Bug fix** (non-breaking change which fixes an issue)
- [ ] **Clean up** (non-breaking change which removes non-working, unmaintained functionality)
- [ ] **Improvement** (non-breaking change which improves existing functionality)
- [ ] **New feature** (non-breaking change which adds functionality)
- [ ] **Breaking change** (fix or feature that will cause existing functionality to change)
- [ ] **Cosmetic change** (non-breaking change that doesn't touch code)
- [ ] **None of the above** (please explain below)

## Checklist:

- [ ] I have read the **[Contributing](https://github.com/xbmc/xbmc/blob/master/docs/CONTRIBUTING.md)** document
- [ ] My code follows the **[Code Guidelines](https://github.com/xbmc/xbmc/blob/master/docs/CODE_GUIDELINES.md)** of this project 
- [ ] My change requires a change to the Wiki documentation
- [ ] I have updated the documentation accordingly

### CODE REVIEW

**Comment by CastagnaIT** [comment]
@phunkyfish can you take a fast look/approve? so that after i can publish the new addon release for Omega
you can see the garbage on the last addon GH release for Nexus

**Comment by phunkyfish** [comment]
Hmmm, very strange. I wonder why it’s not being read correctly by GitHub. It really should just parse that out in the html.

**Comment by phunkyfish** [comment]
Sure merge this and see what the omega realesse looks like. But I think it might fail as I think it expects a single string.

You can always revert it if it doesn’t work.

**Review by phunkyfish — APPROVED** [review]

**Comment by CastagnaIT** [comment]
dont work,
i tried new apttempt with a new PR https://github.com/xbmc/inputstream.adaptive/pull/1485
but still fails... see https://github.com/xbmc/inputstream.adaptive/actions/runs/7975855142
idk what this the problem

**Comment by CastagnaIT** [comment]
FYI i have fixed the release action
see new PR #1486

**Pull request merged**
