### PR TITLE
[DASHTree] Allow content protection without systemid urn

### PR DESCRIPTION
**Pull request by CastagnaIT**
## Description

in the ContentProtection specify system id urn is not mandatory a mistake from the refactor

## Motivation and context

reported on slack
manifest used: [MPDmanifest.txt](https://github.com/xbmc/inputstream.adaptive/files/11610050/MPDmanifest.txt)

## How has this been tested?

just test parse the manifest

## Types of change

- [x] **Bug fix** (non-breaking change which fixes an issue)
- [ ] **Clean up** (non-breaking change which removes non-working, unmaintained functionality)
- [ ] **Improvement** (non-breaking change which improves existing functionality)
- [ ] **New feature** (non-breaking change which adds functionality)
- [ ] **Breaking change** (fix or feature that will cause existing functionality to change)
- [ ] **Cosmetic change** (non-breaking change that doesn't touch code)
- [ ] **None of the above** (please explain below)

## Checklist:

- [x] I have read the **[Contributing](https://github.com/xbmc/xbmc/blob/master/docs/CONTRIBUTING.md)** document
- [x] My code follows the **[Code Guidelines](https://github.com/xbmc/xbmc/blob/master/docs/CODE_GUIDELINES.md)** of this project 
- [ ] My change requires a change to the Wiki documentation
- [ ] I have updated the documentation accordingly

### CODE REVIEW

**Comment by CastagnaIT** [comment]
@hiassoft if you can please test with this PR
you can find common test builds here: https://jenkins.kodi.tv/blue/organizations/jenkins/xbmc%2Finputstream.adaptive/detail/PR-1275/1/artifacts

**Comment by HiassofT** [comment]
It's a bit better now, ORF livestreams start but they aren't decrypted so there's only garbage on screen and lots of audio decoding errors in log.
log: http://ix.io/4x9N
manifest: http://ix.io/4x9Q

As a comparison here's a log using i.a 21.1.0:  http://ix.io/4x9S

**Comment by CastagnaIT** [comment]
@HiassofT seem was miss to search pssh should works now

**Comment by HiassofT** [comment]
Thanks a lot, livestream playback is now fine again :+1:

**Review by glennguy — APPROVED** [review]

**Pull request merged**
