### PR TITLE
Create strings.po

### PR DESCRIPTION
**Pull request by tahirdon**
Hindi-India translations

### CODE REVIEW

**Comment by dagwieers** [comment]
@tahirdon Are you interested in joining the Hindi translation team? You would be the first Kodi add-on translator for Hindi ;-)

**Comment by tahirdon** [comment]
@dagwieers   Yes, would love to do it

**Comment by tahirdon** [comment]
@dagwieers  Can I do something regarding error in "continuous-integration/jenkins/pr-merge"

**Comment by dagwieers** [comment]
No, it is not your problem.
https://jenkins.kodi.tv/blue/organizations/jenkins/peak3d%2Finputstream.adaptive/detail/PR-410/1/pipeline

**Pull request merged**
