### PR TITLE
[Leia][Backport][HLS][Revert] share parameters between master / sub playlists

### PR DESCRIPTION
**Pull request by smf007**
Backport of pull #488 .

### CODE REVIEW

**Comment by matthuisman** [comment]
I have gone ahead and done the cleanup that will make this PR obsolete:
https://github.com/peak3d/inputstream.adaptive/pull/492

**Review by peak3d — CHANGES_REQUESTED** [review]
Even I'm quite sure that this will lead to regression for other streams, I'll let it in if the changes in AdaptiveTree are reverted.
I know that this is maybe currently dead code, but I'm sure that we need it later on.

**Comment by peak3d** [comment]
https://github.com/peak3d/inputstream.adaptive/issues/531

**Comment by smf007** [comment]
Updated as requested.  Is consistent with #488 and tested as noted in #488 with problematic CBC streams.

Scott

**Review by peak3d — APPROVED** [review]

**Pull request merged**
