### PR TITLE
[WebVTT] Read only payl box for text

### LINKED ISSUE #855: Kodi 19: mpd subtitles doesn't always work on discovery+
### Describe the bug

Subtitles on some videos on discovery+ doesn't work properly in Kodi 19.

Here is a clear and concise description of what the problem is:

Every line is displayed as iden1, iden2 and so on.

## Expected Behavior
Here is a clear and concise description of what was expected to happen:

Subtitles to display properly.

## Possible Fix

Latest InputStream Adaptive on Kodi 20 on macOS displays subtitles properly. But latest ISA version available on Kodi nightly ppa (20.0.2) has same problem.

### To Reproduce

1. 
2.
3.

### Debuglog

The debuglog can be found here:
Not working: https://paste.kodi.tv/raw/olimogisaw
Working: https://paste.kodi.tv/wamikiyore.kodi

### MPD/M3U8s/ISM

An example or copy of a manifest (or manifests for HLS - master and variants) can be found here:
Not Working: [master.mpd.txt](https://github.com/xbmc/inputstream.adaptive/files/7705843/master.mpd.txt)
Working: [master2.mpd.txt](https://github.com/xbmc/inputstream.adaptive/files/7705902/master2.mpd.txt)

### Screenshots 
Here are some links or screenshots to help explain the problem:

Screenshot

## Additional context or screenshots (if appropriate)
Here is some additional context or explanation that might help:

### Your Environment
Used Operating system:

 - [ ] Android
 - [ ] iOS
 - [ ] tvOS
 - [x] Linux
 - [x] OSX
 - [ ] Windows
 - [ ] Windows UWP

 - Operating system version/name:
 - Kodi version: Kodi 19
 - inputstream.adaptive version: 19.0.1

*note: Once the issue is made we require you to update it with new information should that be required.
Team Kodi will consider your problem report however, we will not make any promises the problem will be solved.*

### PR DESCRIPTION
**Pull request by CastagnaIT**
A simple way to ignore (known) unmanaged boxes
the parser sucks so I'm not going to do anything to improve it
this is now deprecated anyway

Fix #855

~Needed a test feedback as confirm~

### CODE REVIEW

**Comment by matthuisman** [comment]
this seems to crash my Kodi on Windows.
Was testing as I have a mpd using webvtt that just displays "align:middle line:79% position:68% size:43%" constantly

```
<AdaptationSet id="0" contentType="text" lang="en-US" segmentAlignment="true">
      <Role schemeIdUri="urn:mpeg:dash:role:2011" value="subtitle"/>
      <Representation id="0" bandwidth="1255" codecs="wvtt" mimeType="application/mp4">
        <SegmentTemplate timescale="1000" initialization="PPCOM_SOUTHPARK_0998_1639532438/vtt_init.m4v" media="PPCOM_SOUTHPARK_0998_1639532438/seg_$Number$.m4s" startNumber="1">
          <SegmentTimeline>
            <S t="0" d="6000" r="615"/>
          </SegmentTimeline>
        </SegmentTemplate>
      </Representation>
    </AdaptationSet>
```
Here are the 2x files it manages to download before crashing
[vtt_init.m4v.txt](https://github.com/xbmc/inputstream.adaptive/files/7798547/vtt_init.m4v.txt)
[seg_1.m4s.txt](https://github.com/xbmc/inputstream.adaptive/files/7798545/seg_1.m4s.txt)

**Comment by CastagnaIT** [comment]
i know that crash so it is still in WIP, ATM i am not able to debug ISA then i am stuck

**Comment by matthuisman** [comment]
I tested with Kodi 20 and that worked fine due to the new parser I assume
so not a huge deal :)

**Comment by CastagnaIT** [comment]
@matthuisman i think i have fixed now but i do not know how to test your file

**Comment by matthuisman** [comment]
Tested and works great! thank you @CastagnaIT

**Review by matthuisman — APPROVED** [review]

**Review by glennguy — APPROVED** [review]
Looks good to me, thanks @CastagnaIT

**Comment by matthuisman** [comment]
Does this require another test after latest changes?

**Comment by CastagnaIT** [comment]
no i have add only an additional check to prevent a possible problem

**Comment by matthuisman** [comment]
@CastagnaIT  this all ready to merge?

**Comment by CastagnaIT** [comment]
yes

**Pull request merged**
