### PR TITLE
[cleanups] Cleanups to includes and minor things

### PR DESCRIPTION
**Pull request by CastagnaIT**
## Description

removed some unused includes, foward some other to try to lighten compiler to save some building secs

## Types of change

- [ ] **Bug fix** (non-breaking change which fixes an issue)
- [x] **Clean up** (non-breaking change which removes non-working, unmaintained functionality)
- [ ] **Improvement** (non-breaking change which improves existing functionality)
- [ ] **New feature** (non-breaking change which adds functionality)
- [ ] **Breaking change** (fix or feature that will cause existing functionality to change)
- [ ] **Cosmetic change** (non-breaking change that doesn't touch code)
- [ ] **None of the above** (please explain below)

## Checklist:

- [ ] I have read the **[Contributing](https://github.com/xbmc/xbmc/blob/master/docs/CONTRIBUTING.md)** document
- [ ] My code follows the **[Code Guidelines](https://github.com/xbmc/xbmc/blob/master/docs/CODE_GUIDELINES.md)** of this project 
- [ ] My change requires a change to the Wiki documentation
- [ ] I have updated the documentation accordingly

### CODE REVIEW

**Comment by CastagnaIT** [comment]
@lrusak i have removed shared_ptr on last commit of this pr

**Comment by lrusak** [comment]
> @lrusak i have removed shared_ptr on last commit of this pr

@CastagnaIT see this commit -> https://github.com/lrusak/inputstream.adaptive/commit/ad3b05e8882e503926aa4db0cdf03a2c8ef4292a

I only build tested and briefly runtime tested it.

There seems to be no nullptr checks so I assume that Init is called before anything else is available.

**Comment by CastagnaIT** [comment]
thanks for the example, i had done similar but only for the deconstructor and was not working
i will copy this way but i prefer have pointers than references, yeah its not intended to be allowed have nullptr's
is builded before doing any other addon operation so on "Open"

**Review by glennguy — APPROVED** [review]

**Comment by lrusak** [comment]
> thanks for the example, i had done similar but only for the deconstructor and was not working
> 
> i will copy this way but i prefer have pointers than references, yeah its not intended to be allowed have nullptr's

You should likely be using references here. It doesn't make sense to use pointers if they can never be null anyways. We have quite a few examples of this in core Kodi now. You'll see our CServiceBroker returns references. The places that it returns pointers are likely because the pointer can be null (like windowing) and should always be checked before use.

> is builded before doing any other addon operation so on "Open"

Perfect 👍

**Comment by CastagnaIT** [comment]
> You should likely be using references here. It doesn't make sense to use pointers if they can never be null anyways. We have quite a few examples of this in core Kodi now. You'll see our CServiceBroker returns references. The places that it returns pointers are likely because the pointer can be null (like windowing) and should always be checked before use.

oh i understood ok i will change it

**Pull request merged**
