### PR TITLE
[Properties] Add license_url/license_url_append properties

### PR DESCRIPTION
**Pull request by CastagnaIT**
## Description

This PR add
`inputstream.adaptive.license_url`
`inputstream.adaptive.license_url_append`
an exclusive workaround for PVR binary add-ons

these new properties has same valence of
_[license server URL]_ template field of `inputstream.adaptive.license_key` property

when a value is set on both, the `license_url_append` value will be appended to `license_url` value

the resulting value will replace _[license server URL]_ template field of `inputstream.adaptive.license_key`
also in case the `license_key` has a license url specified.
I choose to not allow the use both at same time to specify the url, to try to avoid confusions.

## Motivation and context

Kodi PVR API has a bug that limit all strings to max 1024 chars
so on each property that exceeds the limit the string is truncated and so ISA get broken property values and the playback fails

this usually is not a big problem because not often exceeds 1024 chars but
`inputstream.adaptive.license_key` property can contains concatenated data,
and when also the url is very long broken will result in a truncated url or license configuration

this solution is intended for Kodi 20 and 21
because also for Kodi 21 case we are not in time to fix kodi PVR API, a real fix will be delayed to future Kodi 22

Ref. Issues:
https://github.com/xbmc/xbmc/issues/23903
https://github.com/xbmc/inputstream.adaptive/issues/1248

**Appropriate changes to PVR binary addons are needed in order to use this workaround,**
atm im aware that Kodi PVR iptvsimple addon use it, so need the changes for Kodi 20/21,
the change is quite simple, instead to set the license url string to the `inputstream.adaptive.license_key` use
`inputstream.adaptive.license_url`
`inputstream.adaptive.license_url_append`
by taking care to split the url in two parts of 1024 chars (max url length of 2048 chars, that in any case should be a common limit used on webbrowsers)

**e.g. before:**
license_key: `http://www.xyz.com/license/...[other chars].../itsverylong/|Content-Type=application/octet-stream|R{SSM}|R`
**after:**
license_key: `|Content-Type=application/octet-stream|R{SSM}|R` (note that need to start with a pipe `|`)
license_url: `http://www.xyz.com/license/...` (split/limit the string to 1024)
license_url_append: `.../itsverylong/` (set here the remaining url chars)

## How has this been tested?

~needed feedbacks~ user confirmed work

## Types of change

- [ ] **Bug fix** (non-breaking change which fixes an issue)
- [ ] **Clean up** (non-breaking change which removes non-working, unmaintained functionality)
- [x] **Improvement** (non-breaking change which improves existing functionality)
- [ ] **New feature** (non-breaking change which adds functionality)
- [ ] **Breaking change** (fix or feature that will cause existing functionality to change)
- [ ] **Cosmetic change** (non-breaking change that doesn't touch code)
- [ ] **None of the above** (please explain below)

## Checklist:

- [ ] I have read the **[Contributing](https://github.com/xbmc/xbmc/blob/master/docs/CONTRIBUTING.md)** document
- [ ] My code follows the **[Code Guidelines](https://github.com/xbmc/xbmc/blob/master/docs/CODE_GUIDELINES.md)** of this project 
- [ ] My change requires a change to the Wiki documentation
- [ ] I have updated the documentation accordingly

### CODE REVIEW

**Comment by nirvana-7777** [comment]
Hi, an excellent idea for a workaround. Thank you for implementing it. I was a bit short in time and will test it asap. Probably next week. Then I will report about the outcome.

**Comment by aicynide** [comment]
Please merge this pr so that I can play tataplay widevine channels

**Comment by aicynide** [comment]
Is the license url character limit unlimited now?

**Comment by CastagnaIT** [comment]
> Please merge this pr so that I can play tataplay widevine channels

will not be merged until someone make a test and provide a feedback with PVR iptvsimple or PVR magenta
with the required changes explained above

> Is the license url character limit unlimited now?

as explained on PR description, NO,
there is a Kodi PVR interface bug

**Comment by CastagnaIT** [comment]
i want remember you that Kodi 21 development cycle is about to be completed
if someone want to see this workaround implemented on Kodi 20, and 21, you need to provide us a feedback to know if works correctly in time

this PR will remain open until the end of next month (after that depends when will be the Kodi 21 official release)
after that time if i don't get any response here nor a feedback, this PR will be closed

alternatively, you can also request to postpone this change for the next Kodi 22,
but the backport will be possible only for Kodi 21, because developments on Kodi 20 branch at that time will be closed

**Comment by nirvana-7777** [comment]
Thanks for kicking me a bit forward :-)

I've updated my environment and can now confirm that it works. I've taken an arbitrary cut at 1000 characters and this is the log:
`2023-11-22 15:26:04.275 T:188235   debug <general>: ADDON: Dll Initializing - InputStream Adaptive
2023-11-22 15:26:04.275 T:188235   debug <general>: SECTION:LoadDLL(/home/basti/.kodi/addons/inputstream.adaptive/inputstream.adaptive.so.21.4.0)
2023-11-22 15:26:04.275 T:188235   debug <general>: Loading: /home/basti/.kodi/addons/inputstream.adaptive/inputstream.adaptive.so.21.4.0
2023-11-22 15:26:04.276 T:188084   debug <general>: Loading settings for pvr://channels/tv/Alle%20Sender@-1/0@pvr.magenta_10301.pvr
2023-11-22 15:26:04.289 T:188067   debug <general>: CPlayerGUIInfo::InitCurrentItem(pvr://channels/tv/Alle%20Sender@-1/0@pvr.magenta_10301.pvr)
2023-11-22 15:26:04.298 T:188235   debug <general>: AddOnLog: inputstream.adaptive: Open()
2023-11-22 15:26:04.298 T:188235   debug <general>: AddOnLog: inputstream.adaptive: Property found "inputstream.adaptive.license_type" value: com.widevine.alpha
2023-11-22 15:26:04.298 T:188235   debug <general>: AddOnLog: inputstream.adaptive: Property found "inputstream.adaptive.license_url" value: [redacted]
2023-11-22 15:26:04.298 T:188235   debug <general>: AddOnLog: inputstream.adaptive: Property found "inputstream.adaptive.license_url_append" value: [redacted]
2023-11-22 15:26:04.298 T:188235   debug <general>: AddOnLog: inputstream.adaptive: Property found "inputstream.adaptive.play_timeshift_buffer" value: false
`
Subsequently the picture is cleared. It would be nice if you could include it to the main branch.
Really thank you very much for your kind efforts again!

**Review by glennguy — APPROVED** [review]

**Pull request merged**
