### PR TITLE
Parse frame rates from HLS master playlists

### PR DESCRIPTION
**Pull request by glennguy**

### CODE REVIEW

**Review by peak3d — APPROVED** [review]

**Review by peak3d — APPROVED** [review]

**Comment by ksooo** [comment]
With this PR applied, I see "23976.000 FPS" in Kodi's Player Info dialog for the first couple of seconds, before it changes to "23.976 FPS". Tested with Disney+, The Mandalorian, S1E1.

**Comment by glennguy** [comment]
@ksooo could you please provide the url for the master hls playlist? Should be similar to eg. https://vod-l3c-oc-east-1.media.dssott.com/ps01/disney/60a600e8-1306-4118-b96b-b0b1f783871a/regular-ctr-sw-0579ca69-dccf-432a-b2d3-afa2cc49cb49.m3u8

**Comment by ksooo** [comment]
http://vod-llc-eu-north-2.media.dssott.com/ps01/disney/60a600e8-1306-4118-b96b-b0b1f783871a/ctr-hdr10-high-7880964d-e657-4a0e-91a3-d2d2fd0344d2.m3u8

There is also an interesting line in my kodi.log:

```
2020-05-17 17:19:51.511 T:25296   ERROR: CVideoPlayerVideo::OpenStream - Invalid framerate 23976, using forced 25fps and just trust timestamps
```

**Comment by matthuisman** [comment]
In the playlist, its **FRAME-RATE=23.976**
I see in the code, that get's timed by 1000 (to remove decimals)
23.976*1000 = 23976
But I assume that's where the timescale is used to divide it later on by 1000?

**Comment by glennguy** [comment]
@ksooo thanks for that!
Found the issue, fixed in #451

**Pull request merged**
