### PR TITLE
Matrix API change to v2.3.0 - Allows upto 256 streams, useful for netflix etc and mime type

### PR DESCRIPTION
**Pull request by phunkyfish**
Do not merge yet.

Part of https://github.com/xbmc/xbmc/pull/17633
https://github.com/xbmc/xbmc/pull/17727

### CODE REVIEW

**Comment by phunkyfish** [comment]
@peak3d the API change is in Kodi so this can be merged and released when you are ready. Matrix only change.

**Comment by phunkyfish** [comment]
As they has not been merged/released will use it for next API change.

**Comment by phunkyfish** [comment]
Ready to merge/release @peak3d

**Comment by orfeous1** [comment]
We wait for peak3d i guess?

**Comment by phunkyfish** [comment]
Yup

**Comment by peak3d** [comment]
Pls. don't pass version changes only PR's.
a.) just changing version does not help, a new tag has to be created, and b.) the Readme.md contains the version.

I'll do the version bump now on my local machine.

**Pull request closed without merging**
