### PR TITLE
Some tree / session cleanups

### PR DESCRIPTION
**Pull request by CastagnaIT**
## Description

some cleanups while investigating on current issues

commits:
1) We want avoid print a log error when an HLS child manifest has not been prepared yet
and ContainerType result as NOTYPE
2) cleanups
3) cleanups
4) Prevent to show empty resolution to GUI, can happens when there is no HLS RESOLUTION info, like on some live streams
5) Removed not needed method argument stream type
6) Removed needRefetch, the reasons behind this of this forced behaviour are unclear to me, `OpenStream` require return value to be true only when there is need to update stream info, but this is already done by the reader with `GetInformation` and extradata if needed is already taken in account. Tested with and without DRM HLS stream not found weirdness. @glennguy if you remember something let me know, also too much old GH history there are no explanations
7) small fix, if there is no CHANNELS info on rendition, fallback to 2 channels
8) as title, reproducible with royal family stream https://cdn-ue1-prod.tsv2.amagi.tv/avod/simplestream-lds-ldtimln/ODYPPCS001EP001/ODYPPCS001EP001.m3u8

## Types of change

- [x] **Bug fix** (non-breaking change which fixes an issue)
- [x] **Clean up** (non-breaking change which removes non-working, unmaintained functionality)
- [ ] **Improvement** (non-breaking change which improves existing functionality)
- [ ] **New feature** (non-breaking change which adds functionality)
- [ ] **Breaking change** (fix or feature that will cause existing functionality to change)
- [ ] **Cosmetic change** (non-breaking change that doesn't touch code)
- [ ] **None of the above** (please explain below)

## Checklist:

- [ ] I have read the **[Contributing](https://github.com/xbmc/xbmc/blob/master/docs/CONTRIBUTING.md)** document
- [ ] My code follows the **[Code Guidelines](https://github.com/xbmc/xbmc/blob/master/docs/CODE_GUIDELINES.md)** of this project 
- [ ] My change requires a change to the Wiki documentation
- [ ] I have updated the documentation accordingly

### CODE REVIEW

**Comment by glennguy** [comment]
Peak3d implemented the needRefetch iirc when he did some refactoring after the initial HLS/WV implementation. I think the real test for this is when periods or reps change but PSSH remains the same (common key for all streams). Disney+ is probably in this case if you still have an account to test with?

**Review by glennguy — APPROVED** [review]

**Comment by matthuisman** [comment]
i emailed @CastagnaIT a disney+ login 10 days ago. can re-send if needed :)

**Comment by CastagnaIT** [comment]
this week im short in time to give to developing
hoping tonight i find some time to make a test with D+ (if login works)

**Comment by CastagnaIT** [comment]
i have tested D+ (thanks @matthuisman works!) with a couple of tvshows having more periods at the near the end of video
and i havent found playback problems, tried also seek backward / forward in the middle of chapters and seem ok

**Pull request merged**
