### PR TITLE
[Leia] Backport Matrix bug fixes

### PR DESCRIPTION
**Pull request by matthuisman**
Backport: 
https://github.com/xbmc/inputstream.adaptive/pull/602
https://github.com/xbmc/inputstream.adaptive/pull/626
https://github.com/xbmc/inputstream.adaptive/pull/564
https://github.com/xbmc/inputstream.adaptive/pull/606
https://github.com/xbmc/inputstream.adaptive/pull/607
https://github.com/xbmc/inputstream.adaptive/pull/575
https://github.com/xbmc/inputstream.adaptive/pull/565
https://github.com/xbmc/inputstream.adaptive/pull/499 & https://github.com/xbmc/inputstream.adaptive/pull/601

this will close: https://github.com/xbmc/inputstream.adaptive/pull/566

builds here:
https://jenkins.kodi.tv/blue/organizations/jenkins/xbmc%2Finputstream.adaptive/detail/PR-634/14/artifacts

### CODE REVIEW

**Comment by matthuisman** [comment]
jenkins build this please

**Comment by matthuisman** [comment]
@glennguy ready for review when your ready :)

@phunkyfish
I know you said just regressions, but I really feel the other PRs are pretty essential to get 18 stable and working with all current add-ons. It will be it's last update so may as well make it as good as possible? It will keep as many devs and users as happy as possible.

**Comment by phunkyfish** [comment]
Is this supposed to push to binary addon repos or not? Or just push there for manual install only?

If you want the push to the binary addon repos the jenkinsfile will need to be updated.

**Comment by glennguy** [comment]
As mentioned on slack can you bring in #499 plus DllHelper.h and the one-line change in main.h?

**Comment by matthuisman** [comment]
did up a test repo:

1) Start with stock Kodi 18.9
2) Enable debug logging
3) Install https://f.mjh.nz/test/plugin.video.rivedila7-Leia.zip (test add-on)
4) Try to play "LA7 Live" - won't work
5) Install repo: https://f.mjh.nz/test/repository.inputstream.adaptive.0.0.1.zip
6) Update Inputstream Adaptive to 2.4.7 (will auto update if updates enabled)
7) Try to play "LA7 Live" - still won't work as bug in 18 keeps using the built-in old .so
   If you skip step 4 - it will play as IA .so wouldn't have been loaded yet
8) Restart Kodi
9) Try to play "LA7 Live" - will work
10) Confirm in log that IA correctly loads 
` /data/user/0/org.xbmc.kodi/cache/lib/libinputstream.adaptive.so`&
`/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/inputstream.adaptive/libssd_wv.so`

Here is my log:
before restart: [kodi.log.txt](https://github.com/xbmc/inputstream.adaptive/files/6289150/kodi.log.txt)
after restart: [kodi.log.txt](https://github.com/xbmc/inputstream.adaptive/files/6289152/kodi.log.txt)

Not a big deal for needing a restart as IA will just keep using the old built-in libinputstream.adaptive.so & libssd_wv.so until its restarted.

**Conclusion - this PR is ready to go!**

**Comment by phunkyfish** [comment]
Well we need to have Matrix/master working from repo first. Once that is working we can bring this in.

@glennguy what is needed on the matrix side?

**Comment by glennguy** [comment]
I'll leave a comment in #601

**Review by phunkyfish — APPROVED** [review]
LGTM

**Pull request merged**
