### PR TITLE
try to parse kid from contentprotection element without schemeIdUri=u…

### PR DESCRIPTION
**Pull request by Pati**
…rn:mpeg:dash:mp4protection:2011

This should fix the issue #243 and #223 , because in some manifests the kid is not part of the contentprotection element with schemeIdUri=urn:mpeg:dash:mp4protection:2011

### CODE REVIEW

**Comment by CastagnaIT** [comment]
can you provide me with a build compiled with this commit?
I tried to compile it but I can't, I'm not good with cpp...

I need to check if it also solves the problem on netflix addon and a high bitrate audio stream
I'm not sure it's the same problem, but i get the same error

**Comment by Pati** [comment]
It depends for which platform are you using. If you are using windows you can download it here:
https://jenkins.kodi.tv/blue/organizations/jenkins/peak3d%2Finputstream.adaptive/detail/PR-246/1/artifacts

**Comment by CastagnaIT** [comment]
thanks I tried but in my case it still does not work, i think it is due to other

**Comment by mifricken** [comment]
@Pati I have the same problem "DecryptSampleData: Decrypt failed with error: 2 and key: XXX...", that's my manifest file:

`<?xml version="1.0" encoding="UTF-8" ?>
<MPD profiles="urn:mpeg:dash:profile:isoff-live:2011" type="dynamic" availabilityStartTime="2011-03-01T00:00:10Z" minimumUpdatePeriod="PT2.0S" minBufferTime="PT2.0S" publishTime="2019-05-02T15:52:04Z" timeShiftBufferDepth="PT2M"
    xmlns="urn:mpeg:dash:schema:mpd:2011"
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="urn:mpeg:dash:schema:mpd:2011 DASH-MPD.xsd">
    <Period start="PT0S" id="1">
        <AdaptationSet mimeType="video/mp4" startWithSAP="1" segmentAlignment="true">
            <ContentProtection schemeIdUri="urn:mpeg:dash:mp4protection:2011" value="cenc" />
            <ContentProtection schemeIdUri="urn:uuid:9a04f079-9840-4286-ab92-e65be0885f95"></ContentProtection>
            <ContentProtection schemeIdUri="urn:uuid:edef8ba9-79d6-4ace-a3c8-27dcd51d21ed"></ContentProtection>
            <SegmentTemplate timescale="10000000" presentationTimeOffset="0" media="$RepresentationID$/Segment-$Time$.m4v" initialization="$RepresentationID$/init.m4i">
                <SegmentTimeline>
                    <S t="2578746041103333" d="20000000" r="59" />
                </SegmentTimeline>
            </SegmentTemplate>
            <Representation width="398" height="224" frameRate="30" codecs="avc1.64000d" scanType="progressive" id="stream_0" bandwidth="360000" />
            <Representation width="640" height="360" frameRate="30" codecs="avc1.64001e" scanType="progressive" id="stream_1" bandwidth="750000" />
            <Representation width="768" height="432" frameRate="30" codecs="avc1.64001e" scanType="progressive" id="stream_2" bandwidth="1100000" />
            <Representation width="960" height="540" frameRate="30" codecs="avc1.64001f" scanType="progressive" id="stream_3" bandwidth="1800000" />
            <Representation width="1280" height="720" frameRate="30" codecs="avc1.640020" scanType="progressive" id="stream_4" bandwidth="3000000" />
            <Representation width="1280" height="720" frameRate="60" codecs="avc1.640020" scanType="progressive" id="stream_5" bandwidth="4500000" />
        </AdaptationSet>
        <AdaptationSet mimeType="audio/mp4" startWithSAP="1" lang="eng" segmentAlignment="true">
            <ContentProtection schemeIdUri="urn:mpeg:dash:mp4protection:2011" value="cenc" />
            <ContentProtection schemeIdUri="urn:uuid:9a04f079-9840-4286-ab92-e65be0885f95"></ContentProtection>
            <ContentProtection schemeIdUri="urn:uuid:edef8ba9-79d6-4ace-a3c8-27dcd51d21ed"></ContentProtection>
            <SegmentTemplate timescale="10000000" presentationTimeOffset="0" media="$RepresentationID$/Segment-$Time$.m4a" initialization="$RepresentationID$/init.m4i">
                <SegmentTimeline>
                    <S t="2578746041476666" d="20480000" />
                    <S t="2578746061956666" d="19200000" />
                    <S t="2578746081156666" d="20480000" r="1" />
                    <S t="2578746122116666" d="19200000" />
                    <S t="2578746141316666" d="20480000" r="1" />
                    <S t="2578746182276666" d="19200000" />
                    <S t="2578746201476666" d="20480000" />
                    <S t="2578746221956666" d="19200000" />
                    <S t="2578746241156666" d="20480000" r="1" />
                    <S t="2578746282116666" d="19200000" />
                    <S t="2578746301316666" d="20480000" r="1" />
                    <S t="2578746342276666" d="19200000" />
                    <S t="2578746361476666" d="20480000" />
                    <S t="2578746381956666" d="19200000" />
                    <S t="2578746401156666" d="20480000" r="1" />
                    <S t="2578746442116666" d="19200000" />
                    <S t="2578746461316666" d="20480000" r="1" />
                    <S t="2578746502276666" d="19200000" />
                    <S t="2578746521476666" d="20480000" />
                    <S t="2578746541956666" d="19200000" />
                    <S t="2578746561156666" d="20480000" r="1" />
                    <S t="2578746602116666" d="19200000" />
                    <S t="2578746621316666" d="20480000" r="1" />
                    <S t="2578746662276666" d="19200000" />
                    <S t="2578746681476666" d="20480000" />
                    <S t="2578746701956666" d="19200000" />
                    <S t="2578746721156666" d="20480000" r="1" />
                    <S t="2578746762116666" d="19200000" />
                    <S t="2578746781316666" d="20480000" r="1" />
                    <S t="2578746822276666" d="19200000" />
                    <S t="2578746841476666" d="20480000" />
                    <S t="2578746861956666" d="19200000" />
                    <S t="2578746881156666" d="20480000" r="1" />
                    <S t="2578746922116666" d="19200000" />
                    <S t="2578746941316666" d="20480000" r="1" />
                    <S t="2578746982276666" d="19200000" />
                    <S t="2578747001476666" d="20480000" />
                    <S t="2578747021956666" d="19200000" />
                    <S t="2578747041156666" d="20480000" r="1" />
                    <S t="2578747082116666" d="19200000" />
                    <S t="2578747101316666" d="20480000" r="1" />
                    <S t="2578747142276666" d="19200000" />
                    <S t="2578747161476666" d="20480000" />
                    <S t="2578747181956666" d="19200000" />
                    <S t="2578747201156666" d="20480000" r="1" />
                </SegmentTimeline>
            </SegmentTemplate>
            <Representation audioSamplingRate="48000" codecs="mp4a.40.2" id="stream_7" bandwidth="96000" />
        </AdaptationSet>
        <AdaptationSet mimeType="audio/mp4" startWithSAP="1" lang="por" segmentAlignment="true">
            <ContentProtection schemeIdUri="urn:mpeg:dash:mp4protection:2011" value="cenc" />
            <ContentProtection schemeIdUri="urn:uuid:9a04f079-9840-4286-ab92-e65be0885f95"></ContentProtection>
            <ContentProtection schemeIdUri="urn:uuid:edef8ba9-79d6-4ace-a3c8-27dcd51d21ed"></ContentProtection>
            <SegmentTemplate timescale="10000000" presentationTimeOffset="0" media="$RepresentationID$/Segment-$Time$.m4a" initialization="$RepresentationID$/init.m4i">
                <SegmentTimeline>
                    <S t="2578746041476666" d="20480000" />
                    <S t="2578746061956666" d="19200000" />
                    <S t="2578746081156666" d="20480000" r="1" />
                    <S t="2578746122116666" d="19200000" />
                    <S t="2578746141316666" d="20480000" r="1" />
                    <S t="2578746182276666" d="19200000" />
                    <S t="2578746201476666" d="20480000" />
                    <S t="2578746221956666" d="19200000" />
                    <S t="2578746241156666" d="20480000" r="1" />
                    <S t="2578746282116666" d="19200000" />
                    <S t="2578746301316666" d="20480000" r="1" />
                    <S t="2578746342276666" d="19200000" />
                    <S t="2578746361476666" d="20480000" />
                    <S t="2578746381956666" d="19200000" />
                    <S t="2578746401156666" d="20480000" r="1" />
                    <S t="2578746442116666" d="19200000" />
                    <S t="2578746461316666" d="20480000" r="1" />
                    <S t="2578746502276666" d="19200000" />
                    <S t="2578746521476666" d="20480000" />
                    <S t="2578746541956666" d="19200000" />
                    <S t="2578746561156666" d="20480000" r="1" />
                    <S t="2578746602116666" d="19200000" />
                    <S t="2578746621316666" d="20480000" r="1" />
                    <S t="2578746662276666" d="19200000" />
                    <S t="2578746681476666" d="20480000" />
                    <S t="2578746701956666" d="19200000" />
                    <S t="2578746721156666" d="20480000" r="1" />
                    <S t="2578746762116666" d="19200000" />
                    <S t="2578746781316666" d="20480000" r="1" />
                    <S t="2578746822276666" d="19200000" />
                    <S t="2578746841476666" d="20480000" />
                    <S t="2578746861956666" d="19200000" />
                    <S t="2578746881156666" d="20480000" r="1" />
                    <S t="2578746922116666" d="19200000" />
                    <S t="2578746941316666" d="20480000" r="1" />
                    <S t="2578746982276666" d="19200000" />
                    <S t="2578747001476666" d="20480000" />
                    <S t="2578747021956666" d="19200000" />
                    <S t="2578747041156666" d="20480000" r="1" />
                    <S t="2578747082116666" d="19200000" />
                    <S t="2578747101316666" d="20480000" r="1" />
                    <S t="2578747142276666" d="19200000" />
                    <S t="2578747161476666" d="20480000" />
                    <S t="2578747181956666" d="19200000" />
                    <S t="2578747201156666" d="20480000" r="1" />
                </SegmentTimeline>
            </SegmentTemplate>
            <Representation audioSamplingRate="48000" codecs="mp4a.40.2" id="stream_6" bandwidth="96000" />
        </AdaptationSet>
    </Period>
</MPD>`

With you need more information, provide me an email or chat. :)

**Comment by peak3d** [comment]
sorry @Pati I saw your PR too late :-( I pushed a fix into the master branch, could you pls. verify that it solves your issue, too ?

**Comment by peak3d** [comment]
@mifricken your mpd does not depend on the issue described here.
Pls. open an own issue report

**Comment by Pati** [comment]
Issue is solved

**Pull request closed without merging**
