### PR TITLE
Fix FourCC creation

### LINKED ISSUE #968: Dolby Vision streams no longer trigger Dolby Vision mode on TV
### Describe the bug
Here is a clear and concise description of what the problem is:

Since version 20.2.0 playing a Dolby Vision stream in an addon no longer triggers Dolby Vision mode on the TV.
This happens with all three addons I tried (Netflix, Disney+ and HBO Max).
With version 20.1.2 this was working as it should.

## Expected Behavior
Here is a clear and concise description of what was expected to happen:

Dolby Vision mode triggered on the TV when playing a Dolby Vision stream.

## Actual Behavior

Dolby Vision mode is not triggered. You can tell the Dolby Vision stream is being played, because the colors have the famous purple and green tints.

### To Reproduce

1. Start Netflix addon from Kodi
2. Choose an episode of a show that has Dolby Vision (I used Altered Carbon Season 1)
3. Play the episode

### Debuglog

The debuglog can be found here:
https://paste.kodi.tv/ucarucakon.kodi

### MPD/M3U8s/ISM

An example or copy of a manifest (or manifests for HLS - master and variants) can be found here:

Not sure how to get the manifest file from the Netflix addon?

### Screenshots 
Here are some links or screenshots to help explain the problem:

## Additional context or screenshots (if appropriate)
Here is some additional context or explanation that might help:

### Your Environment
Used Operating system:

 - [x] Android
 - [ ] iOS
 - [ ] tvOS
 - [ ] Linux
 - [ ] OSX
 - [ ] Windows
 - [ ] Windows UWP

 - Operating system version/name: Nvidia Shield Experience 9.0.2 (Android TV 11)
 - Kodi version: kodi-20220507-74574af3-master-22690-arm64-v8a
 - inputstream.adaptive version: Nexus-9b88f0c (https://jenkins.kodi.tv/blue/organizations/jenkins/xbmc%2Finputstream.adaptive/detail/Nexus/114/artifacts)

*note: Once the issue is made we require you to update it with new information should that be required.
Team Kodi will consider your problem report however, we will not make any promises the problem will be solved.*

### PR DESCRIPTION
**Pull request by glennguy**
Should fix #968 

Big thanks to @MauriceW67 and @Ronny-nerd for helping to find the needle in the giant haystack that was the changes between 20.1.2 -> 20.2.0

### CODE REVIEW

**Comment by glennguy** [comment]
@MauriceW67 @Ronny-nerd could you please try the zips at https://jenkins.kodi.tv/blue/organizations/jenkins/xbmc%2Finputstream.adaptive/detail/PR-984/1/artifacts to see if this fixes the issue?

**Comment by CastagnaIT** [comment]
my failure this time
there are fourcc that are created in the opposite direction so i didn't think here was wrong
small things are the worst...

**Review by CastagnaIT — APPROVED** [review]

**Comment by glennguy** [comment]
Well you've been changing thousands of lines of code, 1 mistake isn't too bad ;)

**Comment by Ronny-nerd** [comment]
Thank you glennguy and the IA Team ...the Dolby Vision mode is now working properly again.

**Comment by MauriceW67** [comment]
@glennguy @CastagnaIT I tested the new fix and for me all is ok too now.

Thanks for all your efforts!

**Pull request merged**
