### PR TITLE
Filled #30161 (greek)

### PR DESCRIPTION
**Pull request by Twilight0**
& fill blank strings with the same values to avoid errors on check scripts

### CODE REVIEW

**Comment by Twilight0** [comment]
Sorry for those mistakes in the last PRs, I had rebased my fork on the wrong commit.

**Comment by dagwieers** [comment]
You don't have to close a PR. If you push your changes to the branch that is tracked by the PR, these updates will automatically be visible in this PR. So simply make the changes, force-push and refresh your page.

**Comment by dagwieers** [comment]
There is one translation missing at the end. Apparently it was only added to the English translation recently.

**Comment by Twilight0** [comment]
> There is one translation missing at the end. Apparently it was only added to the English translation recently.
Indeed, just filled it and I reverted that last string to its former translation. I got confused.

**Pull request merged**
