### PR TITLE
[widevine] add support for linux arm64

### PR DESCRIPTION
**Pull request by tmm1**
## Description

without these changes, the following error is observed:

    Initialize: Failed to load library: libwidevinecdm.so: undefined symbol: __aarch64_ldadd4_acq_rel
    Unable to load widevine shared library (libwidevinecdm.so)

cc #1128 https://github.com/emilsvennesson/script.module.inputstreamhelper/issues/530

for reference:
- https://github.com/devins2518/zig/blob/545c3117ff2f88ee9f29414429a06cedebc0d8c0/lib/compiler_rt/aarch64_outline_atomics.zig#L1421-L1461
- https://github.com/gcc-mirror/gcc/blob/fe4608efc15b881ac908a3f90d7322736495ae72/libgcc/config/aarch64/lse-init.c
- https://github.com/gcc-mirror/gcc/blob/fe4608efc15b881ac908a3f90d7322736495ae72/libgcc/config/aarch64/lse.S
- https://godbolt.org/z/z8W7z1cqx

## Motivation and context

add widevine support for linux arm64

## Types of change

- [ ] **Bug fix** (non-breaking change which fixes an issue)
- [ ] **Clean up** (non-breaking change which removes non-working, unmaintained functionality)
- [x] **Improvement** (non-breaking change which improves existing functionality)
- [ ] **New feature** (non-breaking change which adds functionality)
- [ ] **Breaking change** (fix or feature that will cause existing functionality to change)
- [ ] **Cosmetic change** (non-breaking change that doesn't touch code)
- [ ] **None of the above** (please explain below)

## Checklist:

- [x] I have read the **[Contributing](https://github.com/xbmc/xbmc/blob/master/docs/CONTRIBUTING.md)** document
- [x] My code follows the **[Code Guidelines](https://github.com/xbmc/xbmc/blob/master/docs/CODE_GUIDELINES.md)** of this project 
- [ ] My change requires a change to the Wiki documentation
- [ ] I have updated the documentation accordingly

### CODE REVIEW

**Comment by CastagnaIT** [comment]
thanks, however for next time always use PR template

**Comment by CastagnaIT** [comment]
i fixed PR title and description since now the master branch is Omega, and then the other PR is the relative backport

**Review by glennguy — APPROVED** [review]

**Comment by eqikkwkp25-cyber** [comment]
@glennguy Hello, any plans to merge this to Matrix branch too? Thanks in advance.

**Comment by CastagnaIT** [comment]
@eqikkwkp25-cyber for now we have no plan to backport and/or make new releases for matrix,
some Kodi OS cannot run Widevine arm64 for Matrix so make a backport is not useful
we will try discuss with team on next weeks

**Comment by eqikkwkp25-cyber** [comment]
@CastagnaIT Can you colloborate which Kodi OS cannot run Widevine arm64 for Matrix? Unfortunately i am stuck to Ubuntu 19.10 arm64 with Kodi 19 on a handheld with Rockchip RK3566 (Arkos). Thanks.

**Comment by CastagnaIT** [comment]
@eqikkwkp25-cyber we have investigated and no official Kodi 19 builds are available for arm64, nor the Kodi 20,
and since we have already stopped development for Kodi 19 atm your only solution is make a your custom building of ISAdaptive for kodi 19 by adding on top the patch for widevine arm64 manually (`git cherry-pick commit-hash`)

you need also to manually install the arm64 wv library as explained on this issue:
https://github.com/emilsvennesson/script.module.inputstreamhelper/issues/530

i have written to the ISHelper devs, but their has not give anwers to integrate arm64 support yet
then for now everyone will have to install the library manually

**Pull request merged**
