### PR TITLE
Network toggle + Display resolution update

### PR DESCRIPTION
**Pull request by spyderboy92**

### CODE REVIEW

**Comment by matthuisman** [comment]
@spyderboy92 
does this stop min_bandwidth & max_bandwidth from working?
Trying this Pr, and if I set max bandwidth in settings to 1000, it will still play the highest quality stream.

**Comment by spyderboy92** [comment]
@matthuisman  Nope, I haven't masked the min-max bandwidth. Intention was to have Auto mode with minimal general user settings. If needed I'll mask them.
Thanks

**Comment by matthuisman** [comment]
would be nice to be able to keep the current behaviour if possible?

eg. if min_bandwidth is present, then auto will only change down to that.
And same for max, auto will change up to a maximum bitrate.

0 on minimum (default) = no minimum
0 on maximum  (default) = no maximum

Then an option to turn on /  off auto switching. (default is on)

I know quite a few users who use max bandwidth to limit the amount of data used (data caps on internet).

**Comment by spyderboy92** [comment]
Okay, I will change it. 
Also any more suggestions are welcomed too.

**Comment by matthuisman** [comment]
awesome!

I assume you removed the 'bandwidth.bin' code now that you have a better way of detecting the users bandwidth?

that was a bit confusing anyway as it's behaviour was hidden.
All it was doing is recording the last initial download speed and then using that the next time something is played to choose a quality.

**Comment by Maven85** [comment]
This PR causes Kodi to crash on Android when playing a video using CastagnaIT's Netflix addon.

Tested with Shield TV (Android 9) and Smartphone (Android 10).

**Comment by matthuisman** [comment]
Why / how are you even using a build with this PR? Its not merged...

**Comment by Maven85** [comment]
By taking this PR and then doing my private Kodi build.

**Comment by matthuisman** [comment]
Oh, I'd consider this a draft. Its big change and needs peak3d input but he seems mia at this stage.

**Comment by spyderboy92** [comment]
@matthuisman @Maven85  peak3d had suggested me to clean all PRs and make a new PR with proper commit messages for better reviewing the work, so I will restructure code with clang-format, and seperate cosmetic changes like HD/FHD/ Auto options that I will try to further work upon.

**Comment by matthuisman** [comment]
@spyderboy92
Would love to get your work into the IA Testing add-on (https://github.com/johnny5-is-alive/inputstream.adaptive.testing) that myself and @glennguy manage - to start getting some user feedback.

Are you able to separate the Buffering commits from the rest of the adaptive switching stuff?
Buffer support for a start would be awesome to get in.

**Comment by spyderboy92** [comment]
@matthuisman Sure, will cleaned PR starting with this weekend. Had took a long break.

**Comment by glennguy** [comment]
Hi @spyderboy92, closing this as it's just the halfway milestone PR :)

**Pull request closed without merging**
