### PR TITLE
fix wrong name on Jenkinsfile, must be Matrix, not master

### PR DESCRIPTION
**Pull request by AlwinEsch**

### CODE REVIEW

**Comment by dagwieers** [comment]
And I wonder how we can get an Android/ARM and Linux/ARM (RPi) build for Leia ?

**Comment by ksooo** [comment]
@AlwinEsch What about appveyor.yml and .travis.yml ?

**Comment by AlwinEsch** [comment]
This must be stay in master, this use the clone of https://github.com/xbmc/xbmc direct thats why required there.

**Comment by ksooo** [comment]
> This must be stay in master, this use the clone of https://github.com/xbmc/xbmc direct thats why required there.

 Ah. Okay, then.

**Comment by peak3d** [comment]
This one is obsolete, correct @AlwinEsch ?

**Pull request closed without merging**
